// Usage: PLAYWRIGHT_MODULE=/absolute/path/to/playwright/index.mjs CDP_URL=ws://... node tests/browser-check.mjs
import assert from 'node:assert/strict';
import { writeFile } from 'node:fs/promises';
import { routes } from '../src/screens.mjs';
const { chromium }=await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser=process.env.CDP_URL ? await chromium.connectOverCDP(process.env.CDP_URL) : await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1});
const errors=[],external=[],apiCalls=[];
context.on('request',r=>{if(!r.url().startsWith('http://localhost:4173/')&&!r.url().startsWith('data:'))external.push(r.url());if(['fetch','xhr','websocket'].includes(r.resourceType()))apiCalls.push(r.url());});
await context.addInitScript(()=>{
 window.__gpsCalls=0;
 for(const method of ['getCurrentPosition','watchPosition']) navigator.geolocation[method]=()=>{window.__gpsCalls++;throw Error('GPS forbidden in prototype');};
});
const page=await context.newPage();
page.on('pageerror',e=>errors.push(e.message));
page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
await page.goto('http://localhost:4173/');
assert.equal(new URL(page.url()).pathname,'/auth');
await page.getByRole('link',{name:'Se connecter',exact:true}).click();
await page.getByLabel('Email',{exact:true}).fill('demo@example.test');
await page.getByLabel('Mot de passe',{exact:true}).fill('fictif123');
await page.getByRole('button',{name:'Se connecter',exact:true}).click();
await page.reload();
assert.equal(new URL(page.url()).pathname,'/');
for(const route of Object.keys(routes)){
 await page.goto(`http://localhost:4173${route}`);
 await page.locator('h1').waitFor();
 assert.equal(await page.locator('.bottom-nav a').count(),route.startsWith('/auth')?0:5);
 if(!route.startsWith('/auth'))assert.deepEqual(await page.locator('.bottom-nav a span').allTextContents(),['Accueil','Chiens','Live','Sessions','Profil']);
 assert.equal(await page.evaluate(()=>window.__PISTE_PROTOTYPE__.route),route);
 assert.equal(await page.evaluate(()=>window.__gpsCalls),0);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,route);
}
await page.goto('http://localhost:4173/auth');
assert.equal(await page.locator('input').count(),0);
await page.screenshot({path:new URL('../screenshots/auth-entry-iphone.png',import.meta.url).pathname});
await page.getByRole('link',{name:'Se connecter',exact:true}).click();
await page.screenshot({path:new URL('../screenshots/auth-login-iphone.png',import.meta.url).pathname});
await page.getByRole('button',{name:'Se connecter',exact:true}).click();
assert.equal(await page.locator('[aria-invalid=true]').count(),2);
await page.getByLabel('Email',{exact:true}).fill('demo@example.test');
await page.getByLabel('Mot de passe',{exact:true}).fill('fictif123');
await page.getByRole('button',{name:'Se connecter',exact:true}).click();
assert.equal(new URL(page.url()).pathname,'/');
assert.match(await page.locator('.greeting').innerText(),/Sébastien/);
assert.equal(await page.locator('a[href="/research"]').count(),1);
await page.locator('.bottom-nav a[href="/profile"]').click();
await page.getByRole('button',{name:'Se déconnecter'}).click();
assert.equal(new URL(page.url()).pathname,'/auth');
await page.goto('http://localhost:4173/');
assert.equal(new URL(page.url()).pathname,'/auth');
await page.goto('http://localhost:4173/auth/signup');
await page.screenshot({path:new URL('../screenshots/auth-signup-iphone.png',import.meta.url).pathname});
await page.getByLabel('Prénom',{exact:true}).fill('Camille');
await page.getByLabel('Nom',{exact:true}).fill('Demo');
await page.getByLabel('Email',{exact:true}).fill('camille@example.test');
await page.getByLabel('Mot de passe',{exact:true}).fill('fictif123');
await page.getByLabel('Confirmer le mot de passe').fill('autre123');
await page.getByRole('button',{name:'Créer mon compte'}).click();
assert.equal(await page.locator('#confirmPassword').getAttribute('aria-invalid'),'true');
await page.getByLabel('Confirmer le mot de passe').fill('fictif123');
await page.getByRole('button',{name:'Créer mon compte'}).click();
assert.match(await page.locator('.greeting').innerText(),/Camille/);
assert.equal(await page.locator('a[href="/research"],a[href="/admin"]').count(),0);
await page.locator('.bottom-nav a[href="/profile"]').click();
assert.match(await page.locator('main').innerText(),/Camille/);
await page.reload();
assert.match(await page.locator('main').innerText(),/Camille/);
await page.getByRole('button',{name:'Se déconnecter'}).click();
await page.goto('http://localhost:4173/auth/login');
await page.getByLabel('Email',{exact:true}).fill('demo@example.test');
await page.getByLabel('Mot de passe',{exact:true}).fill('fictif123');
await page.getByRole('button',{name:'Se connecter',exact:true}).click();
await page.goto('http://localhost:4173/auth/forgot');
await page.getByLabel('Email',{exact:true}).fill('demo@example.test');
await page.getByRole('button',{name:'Simuler la récupération'}).click();
assert.match(await page.locator('.auth-result').innerText(),/Aucun email envoyé/);
for(const route of ['/auth','/auth/login','/auth/signup','/']) {
 for(const width of [320,375,390,430,1280]) {
  await page.setViewportSize({width,height:844});
  await page.goto(`http://localhost:4173${route}`);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`${route} ${width}`);
 }
}
await page.setViewportSize({width:390,height:844});
await page.goto('http://localhost:4173/');
const hierarchy=await page.locator('main').evaluate(node=>['.home-intro','.discovery-hero','.feature-grid','.active-sessions','.twin-card','.explore-section'].map(selector=>node.querySelector(selector).getBoundingClientRect().top));
assert.ok(hierarchy.every((top,i)=>i===0||top>hierarchy[i-1]),'canonical section order');
assert.equal(await page.locator('.active-session-card').count(),2);
assert.match(await page.locator('.discovery-cta').innerText(),/Piste opérationnelle/);
assert.equal(await page.locator('.screen-header .home-brand-reference').count(),1);
assert.equal(await page.locator('.home-brand-reference').evaluate(img=>img.complete && img.naturalWidth>0),true);
assert.deepEqual(await page.locator('.feature-tile h3').allTextContents(),['Nouvelle session','Mes pistes','Communauté','Statistiques']);
assert.equal(await page.locator('.feature-tile[href="/new-session"] p').innerText(),'Créer un exercice avec coaching');
const tiles=await page.locator('.feature-tile').evaluateAll(nodes=>nodes.map(n=>n.getBoundingClientRect().toJSON()));
assert.equal(tiles[0].top,tiles[1].top); assert.equal(tiles[2].top,tiles[3].top); assert.ok(tiles[2].top>tiles[0].top);
assert.match(await page.locator('.active-sessions').innerText(),/Crête du Nord/);
const cards=await page.locator('.active-session-card').evaluateAll(nodes=>nodes.map(n=>n.getBoundingClientRect().toJSON()));
assert.equal(cards[0].top,cards[1].top,'two satellite cards beside each other on iPhone');
assert.ok(cards[1].left>cards[0].left);
assert.equal(await page.locator('.session-map img').count(),2);
await page.locator('.active-sessions').scrollIntoViewIfNeeded();
await page.locator('.session-map img').evaluateAll(nodes=>Promise.all(nodes.map(img=>img.decode())));
await page.locator('.twin-card').scrollIntoViewIfNeeded();
await page.locator('.twin-science img').evaluate(img=>img.decode());
await page.evaluate(()=>window.scrollTo(0,0));
await page.screenshot({path:new URL('../screenshots/home-logo-premium-iphone.png',import.meta.url).pathname});
await page.screenshot({path:new URL('../screenshots/home-final-premium-iphone.png',import.meta.url).pathname});
await page.locator('.feature-grid').evaluate(node=>window.scrollTo(0,node.getBoundingClientRect().top+window.scrollY-190));
await page.screenshot({path:new URL('../screenshots/home-four-cards-premium-iphone.png',import.meta.url).pathname});
await page.evaluate(()=>window.scrollTo(0,0));
await page.screenshot({path:new URL('../screenshots/home-logo-reference-iphone.png',import.meta.url).pathname});
await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
await page.screenshot({path:new URL('../screenshots/home-floating-navigation-iphone.png',import.meta.url).pathname});
await page.screenshot({path:new URL('../screenshots/home-canonical-final-iphone.png',import.meta.url).pathname});
await page.screenshot({path:new URL('../screenshots/home-canonical-v2-reference-iphone.png',import.meta.url).pathname});
await page.locator('.active-sessions').evaluate(node=>window.scrollTo(0,node.getBoundingClientRect().top+window.scrollY-160));
await page.screenshot({path:new URL('../screenshots/home-sessions-reference-iphone.png',import.meta.url).pathname});
await page.screenshot({path:new URL('../screenshots/home-sessions-iphone.png',import.meta.url).pathname});
await page.locator('.twin-card').evaluate(node=>window.scrollTo(0,node.getBoundingClientRect().top+window.scrollY-230));
await page.screenshot({path:new URL('../screenshots/home-twin-reference-iphone.png',import.meta.url).pathname});
await page.evaluate(()=>window.scrollTo(0,0));
await page.screenshot({path:new URL('../screenshots/home-canonical-iphone.png',import.meta.url).pathname});
await page.locator('.twin-card').evaluate(node=>window.scrollTo(0,node.getBoundingClientRect().top+window.scrollY-350));
await page.screenshot({path:new URL('../screenshots/home-twin-iphone.png',import.meta.url).pathname});
await page.goto('http://localhost:4173/');
for(const target of ['/new-session','/sessions','/community','/statistics']){
 await page.locator(`.feature-tile[href="${target}"]`).click();
 assert.equal(new URL(page.url()).pathname,target);
 await page.goBack();
}
for(const target of ['/dogs','/live','/sessions','/profile','/']){
 await page.locator(`.bottom-nav a[href="${target}"]`).click();
 assert.equal(await page.locator('.bottom-nav [aria-current="page"]').getAttribute('href'),target);
}
await page.getByRole('button',{name:'Afficher la notification fictive'}).click();
assert.match(await page.locator('#feedback').innerText(),/session fictive/);
await page.locator('.bottom-nav a[href="/sessions"]').click();
await page.getByRole('button',{name:'Terminées',exact:true}).click();
assert.equal(await page.locator('#session-results .session-card').count(),1);
await page.getByRole('searchbox').fill('introuvable');
assert.match(await page.locator('#session-results').innerText(),/Aucune session/);
await page.getByRole('searchbox').fill('lisière');
assert.equal(await page.locator('#session-results .session-card').count(),1);
await page.screenshot({path:new URL('../screenshots/sessions-iphone.png',import.meta.url).pathname});
await page.goto('http://localhost:4173/new-session');
await page.getByRole('button',{name:'Commencer',exact:true}).click();
await page.getByRole('button',{name:/^Normal/}).click();
await page.getByRole('button',{name:'Continuer',exact:true}).click();
await page.getByRole('button',{name:/^Terrain direct/}).click();
await page.getByRole('button',{name:'Continuer',exact:true}).click();
await page.getByRole('button',{name:'Continuer',exact:true}).click();
await page.getByRole('button',{name:'Créer la session',exact:true}).click();
assert.match(await page.locator('h1').innerText(),/Votre session est prête/);
await page.goto('http://localhost:4173/olfactory-twin');
await page.screenshot({path:new URL('../screenshots/twin-iphone.png',import.meta.url).pathname});
await page.goto('http://localhost:4173/');
for(const width of [320,375,390,430,1280]){
 await page.setViewportSize({width,height:844});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`viewport ${width}`);
 const undersized=await page.locator('a:not(.skip-link),button').evaluateAll(nodes=>nodes.filter(n=>{const r=n.getBoundingClientRect();return r.height<44||r.width<44;}).map(n=>n.textContent));
 assert.deepEqual(undersized,[],`touch targets ${width}`);
}
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:new URL('../screenshots/home-iphone-viewport.png',import.meta.url).pathname});
await page.evaluate(()=>window.scrollTo(0,document.body.scrollHeight));
assert.equal(await page.evaluate(()=>document.querySelector('footer').getBoundingClientRect().bottom<=document.querySelector('.bottom-nav').getBoundingClientRect().top),true,'footer above navigation');
await page.screenshot({path:new URL('../screenshots/home-bottom-safearea-iphone.png',import.meta.url).pathname});
await page.screenshot({path:new URL('../screenshots/home-iphone-bottom.png',import.meta.url).pathname});
// Navigation padding uses its measured height, including simulated Safari safe area.
for(const [width,height,inset] of [[320,568,0],[390,664,34],[390,844,34],[430,932,34],[1280,900,0]]) {
 await page.setViewportSize({width,height});
 await page.evaluate(value=>document.querySelector('.bottom-nav').style.bottom=`${value+10}px`,inset);
 await page.evaluate(()=>window.dispatchEvent(new Event('resize')));
 await page.evaluate(()=>window.scrollTo(0,document.body.scrollHeight));
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`safe area ${width}`);
 const layout=await page.evaluate(()=>({footer:document.querySelector('footer').getBoundingClientRect().bottom,nav:document.querySelector('.bottom-nav').getBoundingClientRect().top,padding:parseFloat(getComputedStyle(document.querySelector('main')).paddingBottom),height:document.querySelector('.bottom-nav').getBoundingClientRect().height}));
 assert.ok(layout.footer<=layout.nav && layout.padding>=layout.height,`last content above nav ${width}x${height}`);
}
await page.setViewportSize({width:390,height:844});
await page.evaluate(()=>document.querySelector('.bottom-nav').style.bottom='44px');
await page.evaluate(()=>window.dispatchEvent(new Event('resize')));
await page.evaluate(()=>window.scrollTo(0,document.body.scrollHeight));
await page.screenshot({path:new URL('../screenshots/home-floating-navigation-safearea-iphone.png',import.meta.url).pathname});
await page.screenshot({path:new URL('../screenshots/home-bottom-safearea-iphone.png',import.meta.url).pathname});
assert.deepEqual(errors,[]);assert.deepEqual(external,[]);assert.deepEqual(apiCalls,[]);
const report={routes:Object.keys(routes).length,viewportWidths:[320,375,390,430,1280],auth:'anonymous redirect, login, persistent session, signup, logout, standard permissions, reset passed',homeHierarchy:'intro, hero, tiles, satellite sessions side by side, photo twin, expert passed',bottomSafeArea:'measured navigation, short viewport and 34px inset passed',navigation:'passed',filters:'passed',coaching:'intro, normal mode, direct trace, roles, review and mock creation passed',touchTargets:'44px minimum passed',consoleErrors:errors,externalRequests:external,apiCalls,gpsCalls:0};
await writeFile(new URL('../screenshots/browser-report.json',import.meta.url),JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify(report,null,2));
await context.close();await browser.close();
