import {test} from 'node:test';import assert from 'node:assert/strict';
import {createDraft,updateDraft,createSession,setObservers} from '../src/coaching.mjs';
import {createPreparation,simulate} from '../src/coaching-preparation.mjs';
import {createTracer,advanceTracer} from '../src/coaching-tracer.mjs';
import {createSearch,syncSearch,simulateSearch,advanceSearch,searchView} from '../src/coaching-search.mjs';
const prep=(patch={})=>simulate(createPreparation(createSession(setObservers(updateDraft(createDraft({name:'Vous'},[{id:'nox',name:'Nox'}]),{mode:'normal',traceType:'direct'}),['lea'])).session),{gps:'fresh',...patch});
const ready=(mode='normal')=>{const p=prep({mode});return {p,s:simulateSearch(createSearch(),{phase:'SEARCH_READY'})};};
test('only SEARCH_READY and the designated current SearchActor can start',()=>{for(const phase of ['PREPARATION','LAYING','TRACK_FINISHED','LAYING_WAIT','SEARCH_RUNNING','SEARCH_FINISHED','DEBRIEF'])assert.throws(()=>advanceSearch(simulateSearch(createSearch(),{phase}),prep(),'start'));const {p,s}=ready();assert.equal(advanceSearch(s,p,'start').phase,'SEARCH_RUNNING');for(const role of ['coach','traceur','observer'])assert.throws(()=>advanceSearch(s,simulate(p,{viewerRole:role}),'start'));const wrong=structuredClone(p);wrong.session.roles.driver='alex';assert.throws(()=>advanceSearch(s,wrong,'start'));});
test('canonical search transitions and closed terrain cannot mutate recording',()=>{let {p,s}=ready();assert.throws(()=>advanceSearch(s,p,'finish'));s=advanceSearch(s,p,'start');s=advanceSearch(s,p,'progress');assert.equal(s.seconds,30);assert.equal(s.distance,35);s=advanceSearch(s,p,'finish');assert.equal(s.phase,'SEARCH_FINISHED');assert.throws(()=>advanceSearch(s,p,'progress'));s=advanceSearch(s,p,'debrief');assert.equal(s.phase,'DEBRIEF');assert.throws(()=>advanceSearch(s,p,'start'));assert.throws(()=>advanceSearch(s,simulate(p,{viewerRole:'observer'}),'debrief'));});
test('Traceur state is read-only input and reference never implies physical laying',()=>{let p=prep({viewerRole:'traceur',phase:'ready'}),t=createTracer(),s=createSearch();for(const [action,phase] of [['start','LAYING'],['finish','TRACK_FINISHED'],['in-place','SEARCH_READY']]){t=advanceTracer(t,p,action);const before=structuredClone(t);s=syncSearch(s,p,t);assert.equal(s.phase,phase);assert.deepEqual(t,before);}assert.equal(syncSearch(createSearch(),prep({traceType:'prepared'}),createTracer()).phase,'PREPARATION');});
test('driver projections strip forbidden spatial data, including debrief and derived metrics',()=>{for(const mode of ['normal','simple_blind','full_blind']){let {p,s}=ready(mode);p=simulate(p,{layers:true});s=simulateSearch(s,{fixturePose:true});let v=searchView(s,p);assert.equal(v.markers.some(m=>m.role==='traceur'),mode==='normal');assert.equal(v.paths.some(x=>x.kind==='pose'),mode==='normal');assert.equal(v.arrival!==null,mode==='normal');assert.equal(v.reference!==null,false);if(mode==='full_blind')assert.ok(v.markers.every(m=>m.id===p.viewerId));s=advanceSearch(s,p,'start');s=advanceSearch(s,p,'finish');s=advanceSearch(s,p,'debrief');v=searchView(s,p);assert.ok(!('poseDistance' in v)&&!('tracerPosition' in v)&&!('rawSession' in v));if(mode!=='normal'){assert.equal(v.arrival,null);assert.ok(v.paths.every(x=>x.kind==='search'));assert.equal(v.reference,null);}}});
test('acquisition does not block authorised departure; missing points are never invented or bridged',()=>{let {p,s}=ready();p=simulate(p,{gps:'acquiring'});s=advanceSearch(s,p,'start');assert.deepEqual(s.segments,[]);assert.equal(searchView(s,p).markers.some(m=>m.id===p.viewerId),false);p=simulate(p,{gps:'fresh'});s=advanceSearch(s,p,'progress');s=advanceSearch(s,p,'progress');const old=structuredClone(s.segments);p=simulate(p,{gps:'unavailable'});s=advanceSearch(s,p,'progress');assert.deepEqual(s.segments,old);p=simulate(p,{gps:'fresh'});s=advanceSearch(s,p,'progress');assert.equal(s.segments.length,2);assert.equal(s.segments[1].length,1);assert.equal(s.resumed,true);});
test('freshness explicit and external participants never acquire invented GPS or laying points',()=>{for(const gps of ['acquiring','stale','unavailable']){const {s}=ready();const p=prep({gps,traceurKind:'external'}),v=searchView(simulateSearch(s,{fixturePose:true}),p);assert.equal(v.markers.some(m=>m.role==='traceur'),false);assert.ok(v.paths.every(p=>p.kind!=='pose'));assert.equal(v.orientation,null);}});

test('changing viewer never reassigns Conducteur points and full-blind observers receive no search data',()=>{let {p,s}=ready('full_blind');s=advanceSearch(advanceSearch(s,p,'start'),p,'progress');for(const phase of ['SEARCH_RUNNING','DEBRIEF']){const q=simulate(p,{viewerRole:'observer'}),old=q.points[q.viewerId],v=searchView(simulateSearch(s,{phase}),q);assert.ok(v.paths.every(x=>x.kind!=='search'));const own=v.markers.find(m=>m.id===q.viewerId);assert.deepEqual({x:own.x,y:own.y},old);assert.equal(v.distance,null);assert.equal(v.progress,null);assert.equal(v.action,null);}const q=simulate(p,{mode:'simple_blind',viewerRole:'observer'}),v=searchView(s,q),own=v.markers.find(m=>m.id===q.viewerId);assert.deepEqual({x:own.x,y:own.y},q.points[q.viewerId]);assert.ok(v.paths.some(x=>x.kind==='search'));});

test('successive functions discard Driver action rights and cannot transfer a running recording',()=>{let {p,s}=ready();s=advanceSearch(s,p,'start');const q=structuredClone(p);q.session.roles.driver='alex';q.viewerId='alex';q.team.find(a=>a.id==='alex').functions.push('driver');q.team.find(a=>a.id==='alex').activeFunction='driver';assert.throws(()=>advanceSearch(s,q,'finish'));assert.equal(searchView(s,q).action,null);assert.throws(()=>advanceSearch(s,simulate(p,{viewerRole:'traceur'}),'progress'));});
