import {test} from 'node:test';import assert from 'node:assert/strict';
import {createTrackLibrary,gpxFixtures} from '../src/track-library.mjs';
import {createDraft,updateDraft,selectPreparation,selectCreatorRole,createSession,assignRole} from '../src/coaching.mjs';
import {createPreparation,simulate,preparationView,transition} from '../src/coaching-preparation.mjs';
import {createTracer,advanceTracer,tracerView} from '../src/coaching-tracer.mjs';
import {TracerScreen} from '../src/coaching-tracer-screen.mjs';
const prep=(type='prepared',creator='traceur',solo=false)=>{let d=selectCreatorRole(updateDraft(createDraft({name:'Vous'},[{id:'nox',name:'Nox'}]),{mode:'normal',traceType:type}),creator);if(['prepared','gpx'].includes(type))d=selectPreparation(d,type==='gpx'?gpxFixtures[0]:createTrackLibrary().list()[0]);if(solo)d=assignRole(assignRole(d,'driver','self'),'traceur','self');return simulate(createPreparation(createSession(d).session),{viewerRole:'traceur',gps:'fresh'});};
test('known departure opens the terrain cockpit; arrival and readiness do not start pose',()=>{for(const type of ['prepared','gpx'])for(const creator of ['coach','driver','traceur']){let p=prep(type,creator),s=createTracer();assert.deepEqual(preparationView(p).actions.map(x=>x.id),['approach']);assert.throws(()=>transition(p,'ready'));p=transition(p,'approach');s=advanceTracer(s,p,'approach');assert.equal(s.phase,'approaching');let v=tracerView(s,p);assert.equal(v.action[0],'arrive');assert.equal(v.approach.distance,180);assert.ok(v.paths.some(x=>x.kind==='reference'));assert.throws(()=>advanceTracer(s,p,'start'));s=advanceTracer(s,p,'arrive');assert.equal(tracerView(s,p).action[0],'ready');p=transition(simulate(p,{phase:'arrived'}),'ready');s=advanceTracer(s,p,'ready');assert.equal(s.phase,'before');assert.equal(s.seconds,0);assert.equal(s.distance,0);assert.deepEqual(s.segments,[]);assert.equal(tracerView(s,p).action[0],'start');s=advanceTracer(s,p,'start');assert.equal(s.phase,'active');assert.equal(s.segments[0].length,1);}});
test('direct and none skip approach; only Start records pose',()=>{for(const type of ['direct','none']){let p=prep(type);assert.deepEqual(preparationView(p).actions.map(x=>x.id),['ready']);assert.throws(()=>advanceTracer(createTracer(),p,'approach'));p=transition(p,'ready');assert.deepEqual(createTracer().segments,[]);assert.equal(advanceTracer(createTracer(),p,'start').phase,'active');}});
test('approach has no pose metrics or segments, no fabricated unavailable position',()=>{for(const gps of ['fresh','stale','acquiring','unavailable']){let p=transition(prep('gpx'),'approach');p=simulate(p,{gps});let s=advanceTracer(createTracer(),p,'approach');const v=tracerView(s,p);assert.equal(v.seconds,0);assert.equal(v.distance,0);assert.deepEqual(v.segments,[]);assert.throws(()=>advanceTracer(s,p,'progress'));if(['acquiring','unavailable'].includes(gps)){assert.equal(v.approach.distance,null);assert.ok(!v.markers.some(m=>m.id===v.viewerId));}if(gps!=='fresh')assert.equal(v.orientation,null);assert.doesNotMatch(TracerScreen(s,p),/data-map-path="pose"|data-tracer="back"/);}});
test('solo has identical approach gates; reference and snapshots stay isolated',()=>{let p=prep('prepared','driver',true);const old=structuredClone(p.session.preparation);let s=advanceTracer(createTracer(),transition(p,'approach'),'approach');s=advanceTracer(s,p,'arrive');assert.equal(s.phase,'arrived');assert.deepEqual(p.session.preparation,old);preparationView(p).preparation.start.x=999;assert.deepEqual(p.session.preparation,old);});
test('only current internal Traceur can enter approach; missing actors remain missing',()=>{for(const role of ['coach','driver','observer']){let p=simulate(prep(),{scenario:'observers',viewerRole:role});assert.throws(()=>advanceTracer(createTracer(),p,'approach'));assert.deepEqual(preparationView(p).actions,[]);}let p=simulate(prep(),{positionsPresent:false});let s=advanceTracer(createTracer(),p,'approach');s=advanceTracer(s,p,'arrive');assert.deepEqual(tracerView(s,p).markers,[]);assert.equal(tracerView(s,p).approach.distance,null);});

test('arrival retains its last known position when stale and never invents an unavailable arrival',()=>{for(const gps of ['fresh','unavailable']){let p=transition(prep(),'approach'),s=advanceTracer(createTracer(),p,'approach');p=simulate(p,{gps});s=advanceTracer(s,p,'arrive');const fresh=tracerView(s,p);p=simulate(p,{gps:'stale'});const old=tracerView(s,p).markers.find(m=>m.id===p.viewerId);if(gps==='fresh'){assert.deepEqual({x:old.x,y:old.y},fresh.start);}else assert.notDeepEqual({x:old.x,y:old.y},fresh.start);}});

test('real approach CTA is enabled and calls the existing arrival transition without GPS gating',()=>{for(const gps of ['fresh','acquiring','stale','unavailable']){const p=transition(simulate(prep(),{gps}),'approach'),s=advanceTracer(createTracer(),p,'approach');const v=tracerView(s,p);assert.equal(v.action[0],'arrive');const html=TracerScreen(s,p);assert.match(html,/data-tracer="arrive"/);assert.doesNotMatch(html,/data-tracer="arrive"[^>]*disabled/);const arrived=advanceTracer(s,p,'arrive');assert.equal(arrived.phase,'arrived');assert.equal(arrived.seconds,0);assert.equal(arrived.distance,0);assert.deepEqual(arrived.segments,[]);}});
