import {escapeHTML} from './components.mjs';
import {AdminShell} from './admin-shell.mjs';
const e=value=>escapeHTML(value==null?'—':String(value));
const status=value=>`<span class="admin-status">${e(value)}</span>`;
const btn=(label,href)=>`<a class="admin-button" href="${e(href)}">${e(label)} →</a>`;
const form=(action,targetId,fields,confirmLabel='')=>`<form class="admin-action-form" data-admin-form="${e(action)}" data-target-id="${e(targetId||'')}">${fields}${confirmLabel?`<label class="admin-confirm"><input type="checkbox" name="confirm" required> ${e(confirmLabel)}</label>`:''}<button class="admin-button" type="submit">Confirmer l’action mock</button></form>`;
function table(headers,rows){return `<div class="admin-table-wrap"><table class="admin-table"><thead><tr>${headers.map(h=>`<th>${e(h)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.join(''):`<tr><td colspan="${headers.length}">Aucune donnée</td></tr>`}</tbody></table></div>`;}
function dashboard(data){const members=data.members||[],active=members.filter(m=>m.account_status==='active').length,premium=members.filter(m=>m.premium_entitlement?.source&&m.premium_entitlement?.revoked_at==null).length,jumolf=members.filter(m=>m.jumolf_entitlement?.entitlement!=='none'&&!m.jumolf_entitlement?.revoked_at).length,contributors=members.filter(m=>['active','partial'].includes(m.scientific_contribution?.status)).length;const cards=[['Membres inscrits',members.length,'/admin/members'],['Comptes actifs',active,'/admin/members'],['Premium actifs',premium,'/admin/premium'],['Accès JUMOLF',jumolf,'/admin/premium'],['Contributeurs',contributors,'/admin/scientific'],['Services OK',`${data.serviceSummary.healthy}/${data.serviceSummary.total}`,'/admin/services']];return `<section class="admin-page"><div class="admin-page-title"><h2>Vue générale</h2><p>Indicateurs issus des fixtures locales.</p></div><div class="admin-kpis">${cards.map(([label,value,href])=>`<a class="admin-kpi" href="${href}"><span>${e(label)}</span><strong>${e(value)}</strong></a>`).join('')}</div><div class="admin-dashboard-grid"><section class="admin-panel"><h3>Accès rapides</h3><div class="admin-link-grid">${data.navigation.filter(item=>item.path!=='/admin').map(item=>btn(item.label,item.path)).join('')}</div></section><section class="admin-panel"><h3>Version courante</h3><p>${e(data.version.label)}</p><strong>${e(data.version.app_version)} · ${e(data.version.environment)}</strong></section></div></section>`;}
function membersPage(data){const rows=(data.members||[]).map(m=>`<tr><td><a href="/admin/member/${encodeURIComponent(m.user_id)}">${e(m.display_name)}</a><small>${e(m.user_id)}</small></td><td>${e(m.email)}</td><td>${status(m.account_status)}</td><td>${e(m.premium_entitlement?.source||'Non')}</td><td>${e(m.jumolf_entitlement?.source||'Non')} · ${m.jumolf_enabled?'Activé':'Non activé'}</td><td>${e(m.scientific_role||'—')}</td></tr>`);return `<section class="admin-page"><div class="admin-page-title"><h2>Membres</h2><p>Comptes de démonstration uniquement.</p></div><form class="admin-search" method="get" action="/admin/members"><label>Recherche<input name="query" type="search" value="${e(data.query||'')}" placeholder="Nom, email mock ou identifiant"></label><button class="admin-button">Rechercher</button></form>${table(['Membre / ID interne','Email mock','Compte','Premium','JUMOLF','Rôle scientifique'],rows)}</section>`;}
function memberPage(data,adminRole){
 const m=data.member;
 if(!m)return `<section class="admin-page"><h2>Membre introuvable</h2><p>Aucune fiche ne correspond à cet identifiant mock.</p>${btn('Retour aux membres','/admin/members')}</section>`;
 const reason=`<label>Motif<input name="reason" required maxlength="180"></label>`;
 const permissions=data.permissions||{};
 const sharedCategories=Object.entries(m.scientific_contribution?.categories||{}).filter(([,allowed])=>allowed).map(([key])=>key);
 const consentEvents=(data.consent_history||[]).filter(event=>event.user_id===m.user_id);
 const accountActions=permissions.manageAccount?`${m.account_status==='active'?form('suspend-account',m.user_id,reason,'Je confirme la suspension mock'):''}${m.account_status==='suspended'?form('reactivate-account',m.user_id,'','Je confirme la réactivation mock'):''}`:'';
 const deleteAction=permissions.permanentDelete&&m.account_status!=='deleted_mock'?form('delete-account',m.user_id,reason,'Je confirme le passage en supprimé mock'):'';
 const entitlementActions=permissions.manageEntitlements?`${form('grant-premium',m.user_id,`<label>Durée<select name="duration"><option value="permanent">Permanent</option><option value="7">7 jours</option><option value="30">30 jours</option><option value="365">1 an</option><option value="custom">Date personnalisée</option></select></label><label>Expiration personnalisée<input name="expires_at" type="datetime-local"></label><label>Note<input name="note"></label>`)}${form('revoke-premium',m.user_id,reason,'Je confirme le retrait Premium')}${form('grant-jumolf',m.user_id,`<label>Durée<select name="duration"><option value="permanent">Permanent</option><option value="30">30 jours</option><option value="365">1 an</option><option value="custom">Date personnalisée</option></select></label><label>Expiration personnalisée<input name="expires_at" type="datetime-local"></label><label>Note<input name="note"></label>`)}${form('revoke-jumolf',m.user_id,reason,'Je confirme la révocation JUMOLF')}`:'';
 const scienceActions=permissions.manageScientificRoles?`<form class="admin-action-form" data-admin-form="assign-scientific-role" data-target-id="${e(m.user_id)}"><label>Attribuer un rôle<select name="role"><option value="researcher">Chercheur</option><option value="scientific_reader">Lecteur scientifique</option></select></label>${reason}<label class="admin-confirm"><input type="checkbox" name="confirm" required> Je confirme l’attribution mock</label><button class="admin-button">Attribuer le rôle</button></form>${form('revoke-scientific-role',m.user_id,reason,'Je confirme la révocation scientifique')}`:'';
 const deletionActions=permissions.requestDeletion?`${form('request-account-deletion',m.user_id,reason,'Je confirme la demande de suppression de compte mock')}${form('request-personal-data-deletion',m.user_id,reason,'Je confirme la demande de suppression des données personnelles mock')}${form('request-corpus-deletion',m.user_id,reason,'Je confirme la demande de retrait du corpus mock')}${form('request-access-revocation',m.user_id,reason,'Je confirme la demande de retrait des accès mock')}`:'';
 const roleForm=permissions.manageAdminRoles&&adminRole==='owner_admin'?`<form class="admin-action-form" data-admin-form="set-admin-role" data-target-id="${e(m.user_id)}"><label>Rôle Admin<select name="role"><option value="">Aucun</option><option value="admin">Admin</option><option value="support_admin">Support</option><option value="readonly_admin">Lecture seule</option></select></label>${reason}<label class="admin-confirm"><input type="checkbox" name="confirm" required> Je confirme la modification du rôle Admin</label><button class="admin-button">Modifier le rôle Admin</button></form>`:'';
 return `<section class="admin-page"><div class="admin-page-title"><a href="/admin/members">← Membres</a><h2>${e(m.display_name)}</h2><p>Identifiant interne · <code>${e(m.user_id)}</code></p></div><div class="admin-detail-grid">
 <article class="admin-panel"><h3>Compte</h3><dl><div><dt>Email mock</dt><dd>${e(m.email)}</dd></div><div><dt>Inscription</dt><dd>${e(m.joined_at)}</dd></div><div><dt>Dernier accès mock</dt><dd>${e(m.last_access_at)}</dd></div><div><dt>Statut</dt><dd>${status(m.account_status)}</dd></div></dl><p>${m.dog_count} chien(s) · ${m.session_count} session(s) · résumé uniquement</p>${accountActions}${deleteAction}</article>
 <article class="admin-panel"><h3>Premium &amp; JUMOLF</h3><dl><div><dt>Premium</dt><dd>${e(m.premium_entitlement?.source||'Non actif')}</dd></div><div><dt>JUMOLF</dt><dd>${e(m.jumolf_entitlement?.source||'Aucun accès')} · ${m.jumolf_enabled?'activé par le membre':'non activé'}</dd></div><div><dt>Expiration</dt><dd>${e(m.jumolf_entitlement?.expires_at||'Aucune')}</dd></div><div><dt>Onboarding</dt><dd>${m.jumolf_onboarding_completed?'Terminé':'Non terminé'}</dd></div></dl>${entitlementActions}<p class="admin-note">Attribuer un accès ne peut jamais activer JUMOLF au nom du membre.</p></article>
 <article class="admin-panel"><h3>Recherche scientifique</h3><p>Consentement : <strong>${e(m.scientific_contribution?.status||'Désactivée')}</strong></p><p>Catégories autorisées : ${sharedCategories.length?sharedCategories.map(e).join(', '):'Aucune'} · OPS ${m.scientific_contribution?.ops_enabled?'autorisé':'non partagé'}</p><details><summary>Historique du consentement</summary><ul>${consentEvents.map(event=>`<li>${e(event.timestamp)} · ${e(event.status)} · ${e(event.version)}</li>`).join('')||'<li>Aucun événement mock.</li>'}</ul></details><p>Autorisations consultables, jamais modifiables ici. Rôle scientifique : ${e(m.scientific_role||'Aucun')}</p>${scienceActions}${roleForm}</article>
 <article class="admin-panel"><h3>Opérations distinctes simulées</h3><p>Chaque demande est indépendante; aucune donnée n’est supprimée par ce prototype.</p>${deletionActions}</article></div></section>`;
}
function premiumPage(data){const rows=data.members.map(m=>`<tr><td><a href="/admin/member/${encodeURIComponent(m.user_id)}">${e(m.display_name)}</a></td><td>${e(m.premium_entitlement?.source||'—')}</td><td>${e(m.jumolf_entitlement?.source||'—')}</td><td>${m.jumolf_enabled?'Activé':'Non activé'}</td><td>${e(m.jumolf_entitlement?.expires_at||'Sans expiration')}</td></tr>`);return `<section class="admin-page"><h2>Premium &amp; JUMOLF</h2><p>Entitlements, activation et provenance restent séparés.</p>${table(['Membre','Premium','Source JUMOLF','Activation membre','Expiration'],rows)}<section class="admin-panel"><h3>Historique des entitlements</h3>${table(['Date','Membre','Type','Action','Source'],data.entitlement_history.map(row=>`<tr><td>${e(row.timestamp)}</td><td>${e(row.target_id)}</td><td>${e(row.kind)}</td><td>${e(row.action)}</td><td>${e(row.source)}</td></tr>`))}</section></section>`;}
function codesPage(data){
 const canManage=data.permissions?.manageCodes===true;
 const rows=data.codes.map(c=>{
  const actions=!canManage?'Lecture seule':['revoked','deleted'].includes(c.status)?'Terminé':form('revoke-code',c.id,`<label>Motif<input name="reason" required></label>`,'Je confirme la révocation du code')+form('deactivate-code',c.id,'','Je confirme la désactivation mock')+form('duplicate-code',c.id,`<label>Nouveau code<input name="code" required></label>`)+form('extend-code',c.id,`<label>Nouvelle expiration<input name="expires_at" type="datetime-local" required></label>`);
  return `<tr><td><code>${e(c.code)}</code><small>${e(c.id)}</small></td><td>${status(c.status)}</td><td>${c.uses_count}/${e(c.max_uses)}</td><td>${e(c.expires_at||'Sans expiration')}</td><td>${e(c.grant_type)} · ${e(c.entitlement_duration_days||'permanent')}</td><td>${e(c.campaign||'—')}</td><td><div class="admin-code-actions">${actions}${form('delete-code',c.id,`<label>Motif<input name="reason" required></label>`,'Je confirme l’archivage mock du code')}</div></td></tr>`;
 });
 return `<section class="admin-page"><h2>Codes JUMOLF</h2><p>Catalogue partagé avec le formulaire d’accès JUMOLF. Simulation Admin.</p><section class="admin-panel"><h3>Créer un code</h3>${canManage?`<form class="admin-action-form" data-admin-form="create-code"><label>Code<input name="code" required></label><label>Nombre d’utilisations<input name="max_uses" type="number" min="1" value="10" required></label><label>Type d’accès<select name="grant_type"><option value="permanent">Permanent</option><option value="temporary">Temporaire</option></select></label><label>Durée entitlement (jours)<input name="entitlement_duration_days" type="number" min="1"></label><label>Expiration du code<input name="expires_at" type="datetime-local"></label><label>Campagne<input name="campaign"></label><label>Note interne<input name="note"></label><button class="admin-button">Créer le code</button></form><form class="admin-action-form" data-admin-form="create-code-batch"><h4>Créer plusieurs codes</h4><label>Préfixe<input name="prefix" value="BETA"></label><label>Nombre<input name="count" type="number" min="1" max="100" value="10"></label><label>Utilisations par code<input name="max_uses" type="number" min="1" value="1"></label><button class="admin-button">Créer le lot mock</button></form>`:`<p>Lecture seule pour ce rôle.</p>`}</section>${table(['Code / ID','Statut','Usages','Expiration code','Entitlement','Campagne','Action'],rows)}</section>`;
}
function scientificPage(data){return `<section class="admin-page"><h2>Gouvernance scientifique</h2><p>Les consentements appartiennent aux membres et sont en lecture seule ici.</p><div class="admin-kpis"><div class="admin-kpi"><span>Contributeurs</span><strong>${data.scientific_roles.filter(r=>r.status==='active').length}</strong></div><div class="admin-kpi"><span>Rôles scientifiques</span><strong>${data.scientific_roles.length}</strong></div><div class="admin-kpi"><span>Exclusions mock</span><strong>${data.corpus_governance.length}</strong></div></div>${table(['Membre pseudonymisé','Rôle','Statut','Accordé par','Date'],data.scientific_roles.map(r=>`<tr><td>${e(r.user_id)}</td><td>${e(r.role)}</td><td>${e(r.status)}</td><td>${e(r.granted_by)}</td><td>${e(r.granted_at)}</td></tr>`))}<details class="admin-panel"><summary>Historique des rôles scientifiques</summary>${table(['Membre','Action','Rôle','Acteur','Date'],(data.scientific_role_history||[]).map(r=>`<tr><td>${e(r.user_id)}</td><td>${e(r.action)}</td><td>${e(r.role)}</td><td>${e(r.actor_id)}</td><td>${e(r.timestamp)}</td></tr>`))}</details><article class="admin-panel"><h3>Gouvernance du corpus</h3><p>Les actions ci-dessous ne modifient jamais le consentement source.</p>${data.permissions?.governCorpus?`<form class="admin-action-form" data-admin-form="suspend-corpus"><label>ID pseudonymisé de la contribution<input name="targetId" required></label><label>Motif<input name="reason" required></label><label class="admin-confirm"><input type="checkbox" name="confirm" required> Je confirme la suspension d’inclusion mock</label><button class="admin-button">Suspendre l’inclusion</button></form><form class="admin-action-form" data-admin-form="exclude-session"><label>ID pseudonymisé de session<input name="targetId" required></label><label>Motif sécurité<input name="reason" required></label><label class="admin-confirm"><input type="checkbox" name="confirm" required> Je confirme l’exclusion mock</label><button class="admin-button">Exclure la session</button></form>`:`<p>Lecture seule pour ce rôle.</p>`}</article><p class="admin-note">Aucune action de cette page ne peut activer un consentement utilisateur.</p></section>`;}
function servicesPage(data){return `<section class="admin-page"><h2>Services</h2><p class="admin-simulation-badge">Simulation Admin · aucune connexion externe</p><div class="admin-service-grid">${data.services.map(s=>`<article class="admin-panel"><h3>${e(s.name)}</h3>${status(s.status)}<p>${e(s.message)}</p><small>Dernière vérification mock · ${e(s.checked_at)} · Latence ${e(s.latency_ms)} ms</small></article>`).join('')}</div><h3>Quotas mock</h3><div class="admin-kpis">${data.quotas.map(q=>`<div class="admin-kpi"><span>${e(q.name)}</span><strong>${e(q.status)}</strong></div>`).join('')}</div></section>`;}
function deploymentsPage(data){return `<section class="admin-page"><h2>Déploiements &amp; versions</h2><p>Simulation Admin · données en lecture seule.</p><h3>${e(data.version.label)}</h3>${table(['Environnement','Version','Build','SHA mock','Date','Statut','Notes'],data.deployments.map(d=>`<tr><td>${e(d.environment)}</td><td>${e(d.version)}</td><td>${e(d.build)}</td><td>${e(d.sha)}</td><td>${e(d.date)}</td><td>${e(d.status)}</td><td>${e(d.notes)}</td></tr>`))}</section>`;}
function errorsPage(data){return `<section class="admin-page"><h2>Erreurs, diagnostics &amp; alertes</h2><p>Simulation Admin · fixtures locales en lecture seule.</p><form class="admin-search" method="get" action="/admin/errors"><label>Sévérité<select name="severity"><option value="">Toutes</option><option>error</option><option>warning</option><option>info</option></select></label><button class="admin-button">Filtrer</button></form>${table(['Date','Sévérité','Module','Message','Contexte','Statut'],data.errors.map(x=>`<tr><td>${e(x.timestamp)}</td><td>${e(x.severity)}</td><td>${e(x.module)}</td><td>${e(x.message)}</td><td>${e(x.context)}</td><td>${e(x.status)}</td></tr>`))}<div class="admin-detail-grid">${data.diagnostics.map(x=>`<article class="admin-panel"><h3>${e(x.label)} · ${e(x.status)}</h3><p>${e(x.message)}</p></article>`).join('')}</div>${data.alerts.map(x=>`<p class="admin-note">${e(x.message)}</p>`).join('')}</section>`;}
function auditPage(data){return `<section class="admin-page"><h2>Audit Admin</h2><p>Journal local append-only.</p>${table(['Horodatage','Acteur','Rôle','Action','Cible','Motif'],data.audit.slice().reverse().map(x=>`<tr><td>${e(x.timestamp)}</td><td>${e(x.actor_id)}</td><td>${e(x.actor_role)}</td><td>${e(x.action)}</td><td>${e(x.target_type)} · ${e(x.target_id)}</td><td>${e(x.reason||'—')}</td></tr>`))}</section>`;}
export function AdminScreen({route,model}){
 if(!route)return '';
 if(!model?.access?.allowed)return `<section class="admin-restricted"><span class="admin-eyebrow">ESPACE PRIVÉ</span><h2>Accès restreint</h2><p>Ce profil mock ne dispose pas d’un rôle Admin.</p></section>`;
 const data=model.data||{};const pages={dashboard:dashboard(data),members:membersPage(data),member:memberPage(data,model.access.role),premium:premiumPage(data),codes:codesPage(data),scientific:scientificPage(data),services:servicesPage(data),deployments:deploymentsPage(data),errors:errorsPage(data),audit:auditPage(data),unknown:'<section class="admin-page"><h2>Page Admin introuvable</h2></section>'};
 return AdminShell(pages[route.type]||pages.unknown,route,data.navigation||[]);
}
