import {assertAdminAction,adminActorFor,adminAccessFor,canAdminAct} from './admin-access.mjs';
import {createAdminFixtures} from './admin-fixtures.mjs';
import {appendAdminAudit} from './admin-audit.mjs';
import {redeemAccessCode} from './jumolf-entitlement.mjs';

const clone=value=>structuredClone(value);
const roleAssignments=members=>Object.fromEntries(members.filter(member=>member.admin_role).map(member=>[member.user_id,member.admin_role]));
const requiredConfirmation=(confirmed)=>{if(!confirmed)throw new Error('confirmation_required');};

export function createAdminStore({clock=()=>new Date().toISOString(),fixtures=createAdminFixtures()}={}){
 const state=clone(fixtures);
 const actorFor=actor=>adminActorFor(actor,roleAssignments(state.members));
 const requireAction=(actor,action,targetId=null)=>assertAdminAction(actorFor(actor),action,{targetId,roleAssignments:roleAssignments(state.members)});
 const memberById=id=>state.members.find(member=>member.user_id===id);
 const append=(actor,action,targetType,targetId,before,after,reason='')=>appendAdminAudit(state,{actor:actorFor(actor),action,targetType,targetId,before,after,reason,timestamp:clock()});
 const findCode=code=>state.codes.find(item=>item.code.toLocaleUpperCase()===String(code||'').trim().toLocaleUpperCase());
 const snapshot=actor=>{requireAction(actor,'read_dashboard');return clone(state);};
 const updateMember=(actor,member,action,after,reason='')=>{const before=clone(member);Object.assign(member,clone(after));append(actor,action,'member',member.user_id,before,member,reason);return clone(member);};
 const confirmedReason=(options={},reasonRequired=true)=>{requiredConfirmation(options.confirmed);if(reasonRequired&&!String(options.reason||'').trim())throw new Error('reason_required');};
 const entitlement=(actor,targetId,kind,record,action,options={})=>{
  requireAction(actor,action,targetId);const member=memberById(targetId);if(!member)throw new Error('member_not_found');
  if(kind==='jumolf'&&record?.jumolf_enabled===true)throw new Error('admin_cannot_activate_jumolf');
  if(action==='revoke_premium'||action==='revoke_jumolf')confirmedReason(options);
  const key=kind==='premium'?'premium_entitlement':'jumolf_entitlement',before=clone(member[key]);
  if(action.startsWith('revoke_'))member[key]={...clone(before||{}),entitlement:'none',revoked_at:clock(),revoked_by:actorFor(actor).user_id};
  else member[key]={...clone(record),source:record.source||'admin_grant',granted_by:actorFor(actor).user_id,granted_at:clock(),revoked_at:null};
  if(kind==='jumolf'&&action==='grant_jumolf'&&record?.entitlement==='none')throw new Error('invalid_entitlement');
  const event={event_id:`entitlement-${state.entitlement_history.length+1}`,target_id:targetId,kind,action:action.startsWith('revoke_')?'revoked':record?.action==='extended'?'extended':'granted',before,after:clone(member[key]),actor_id:actorFor(actor).user_id,source:member[key].source,reason:String(options.reason||''),timestamp:clock()};
  state.entitlement_history.push(event);append(actor,`${kind}_${event.action}`,'member',targetId,before,member[key],options.reason||'');return clone(member);
 };
 function mutateCode(actor,action,code,after,options={}){
  requireAction(actor,'manage_codes');const index=state.codes.findIndex(row=>row.id===code.id);if(index<0)throw new Error('code_not_found');
  if(['revoked','deleted'].includes(action))confirmedReason(options);
  const before=clone(state.codes[index]);state.codes[index]={...before,...clone(after),updated_at:clock(),updated_by:actorFor(actor).user_id};
  append(actor,`code_${action}`,'code',code.id,before,state.codes[index],options.reason||'');return clone(state.codes[index]);
 }
 return Object.freeze({
  snapshot,resolveActor:actor=>actorFor(actor),accountIsActive:userId=>memberById(userId)?.account_status==='active',accessFor:actor=>adminAccessFor(actorFor(actor),roleAssignments(state.members)),canAct:(actor,action,targetId=null)=>canAdminAct(actorFor(actor),action,{targetId,roleAssignments:roleAssignments(state.members)}),assertAction:(actor,action,targetId=null)=>requireAction(actor,action,targetId),listCodes(actor){requireAction(actor,'read_codes');return clone(state.codes);},listAudit(actor){requireAction(actor,'read_audit');return clone(state.audit);},
  listMembers(actor,filters={}){requireAction(actor,'read_members');let rows=state.members.map(clone);const query=String(filters.query||'').trim().toLocaleLowerCase();if(query)rows=rows.filter(m=>[m.display_name,m.email,m.user_id].some(value=>String(value||'').toLocaleLowerCase().includes(query)));for(const [key,value] of Object.entries(filters)){if(key==='query'||value==null||value==='')continue;if(key==='admin_role')rows=rows.filter(m=>m.admin_role===value);else if(key==='scientific_role')rows=rows.filter(m=>m.scientific_role===value);else if(key==='premium')rows=rows.filter(m=>Boolean(m.premium_entitlement?.source)===Boolean(value));else if(key==='jumolf')rows=rows.filter(m=>(m.jumolf_entitlement?.entitlement!=='none')===Boolean(value));else if(key==='contributor')rows=rows.filter(m=>['active','partial'].includes(m.scientific_contribution?.status)===Boolean(value));else if(key in mFilterKeys)rows=rows.filter(m=>m[mFilterKeys[key]]===value);}return rows;},
  getMember(actor,id){requireAction(actor,'read_member');const member=memberById(id);return member?clone(member):null;},
  eventsForMember(actor,id){requireAction(actor,'read_audit');return clone(state.audit.filter(event=>event.target_id===id));},
  setAccountStatus(actor,id,status,options={}){const actions={suspended:'suspend_account',active:'reactivate_account',deletion_pending_mock:'request_account_deletion',deleted_mock:'permanent_mock_delete'};const action=actions[status];if(!action)throw new Error('invalid_account_status');requireAction(actor,action,id);const member=memberById(id);if(!member)throw new Error('member_not_found');if(status!=='active')confirmedReason(options,status!=='deletion_pending_mock');return updateMember(actor,member,`account_${status}`,{account_status:status,account_status_reason:String(options.reason||'')},options.reason||'');},
  requestDeletionOperation(actor,id,operation,options={}){const action=operation==='account'?'request_account_deletion':operation==='personal_data'?'request_personal_data_deletion':operation==='corpus'?'suspend_corpus_inclusion':operation==='access'?'revoke_jumolf':null;if(!action)throw new Error('invalid_deletion_operation');requireAction(actor,action,id);confirmedReason(options);const member=memberById(id);if(!member)throw new Error('member_not_found');const row={request_id:`deletion-${state.deletion_requests.length+1}`,target_id:id,operation,status:'requested_mock',requested_by:actorFor(actor).user_id,reason:String(options.reason),created_at:clock()};state.deletion_requests.push(row);append(actor,`request_${operation}_deletion`,'member',id,null,row,options.reason);return clone(row);},
  grantPremium(actor,id,record,options={}){return entitlement(actor,id,'premium',record,'grant_premium',options);},
  revokePremium(actor,id,options={}){return entitlement(actor,id,'premium',null,'revoke_premium',options);},
  grantJumolf(actor,id,record,options={}){return entitlement(actor,id,'jumolf',record,'grant_jumolf',options);},
  revokeJumolf(actor,id,options={}){return entitlement(actor,id,'jumolf',null,'revoke_jumolf',options);},
  setAdminRole(actor,id,role,options={}){requireAction(actor,'manage_admin_roles',id);if(role!==null&&!['admin','support_admin','readonly_admin'].includes(role))throw new Error('invalid_admin_role');const member=memberById(id);if(!member)throw new Error('member_not_found');confirmedReason(options);return updateMember(actor,member,'admin_role_changed',{admin_role:role},options.reason);},
  setScientificConsent(){throw new Error('consent_owner_only');},
  governCorpus(actor,id,operation,options={}){const action=operation==='suspend'?'suspend_corpus_inclusion':operation==='exclude_session'?'exclude_corpus_session':null;if(!action)throw new Error('invalid_corpus_action');requireAction(actor,action,id);confirmedReason(options);const row={governance_id:`corpus-governance-${state.corpus_governance.length+1}`,target_id:id,operation,status:operation==='suspend'?'suspended_mock':'excluded_sensitive',actor_id:actorFor(actor).user_id,reason:String(options.reason),created_at:clock()};state.corpus_governance.push(row);append(actor,`corpus_${operation}`,'corpus_item',id,null,row,options.reason);return clone(row);},
  assignScientificRole(actor,id,role,options={}){requireAction(actor,'grant_scientific_role',id);if(!['researcher','scientific_reader'].includes(role))throw new Error('invalid_scientific_role');confirmedReason(options);const member=memberById(id);if(!member)throw new Error('member_not_found');const before=member.scientific_role;member.scientific_role=role;const row={user_id:id,role,granted_by:actorFor(actor).user_id,granted_at:clock(),expires_at:options.expires_at||null,status:'active'};state.scientific_roles=state.scientific_roles.filter(item=>item.user_id!==id);state.scientific_roles.push(row);const event={event_id:`science-role-event-${state.scientific_role_history.length+1}`,user_id:id,action:'granted',role,actor_id:actorFor(actor).user_id,reason:String(options.reason||''),timestamp:clock(),expires_at:row.expires_at};state.scientific_role_history.push(event);append(actor,'scientific_role_granted','member',id,{scientific_role:before},row,options.reason);return clone(row);},
  revokeScientificRole(actor,id,options={}){requireAction(actor,'revoke_scientific_role',id);confirmedReason(options);const member=memberById(id);if(!member)throw new Error('member_not_found');const before=member.scientific_role;member.scientific_role=null;state.scientific_roles=state.scientific_roles.map(item=>item.user_id===id?{...item,status:'revoked',revoked_by:actorFor(actor).user_id,revoked_at:clock()}:item);const event={event_id:`science-role-event-${state.scientific_role_history.length+1}`,user_id:id,action:'revoked',role:before,actor_id:actorFor(actor).user_id,reason:String(options.reason||''),timestamp:clock()};state.scientific_role_history.push(event);append(actor,'scientific_role_revoked','member',id,{scientific_role:before},{scientific_role:null},options.reason);return clone(member);},
  createCode(actor,input){requireAction(actor,'create_code');const code=String(input?.code||'').trim().toLocaleUpperCase();if(!code)throw new Error('code_required');if(state.codes.some(row=>row.code===code))throw new Error('code_exists');if(!Number.isInteger(input.max_uses)||input.max_uses<1)throw new Error('invalid_max_uses');if(!['temporary','permanent'].includes(input.grant_type||'permanent'))throw new Error('invalid_grant_type');if((input.grant_type||'permanent')==='temporary'&&(!Number.isInteger(input.entitlement_duration_days)||input.entitlement_duration_days<1))throw new Error('temporary_duration_required');if(input.expires_at&&!Number.isFinite(Date.parse(input.expires_at)))throw new Error('invalid_code_expiration');const row={id:input.id||`admin-code-${state.codes.length+1}`,code,status:'active',created_by:actorFor(actor).user_id,created_at:clock(),expires_at:input.expires_at||null,max_uses:input.max_uses,uses_count:0,grant_type:input.grant_type||'permanent',entitlement_duration_days:input.entitlement_duration_days??null,revoked_at:null,note_admin:String(input.note||''),campaign:String(input.campaign||''),last_used_at:null};state.codes.push(row);append(actor,'code_created','code',row.id,null,row,input.reason||'');return clone(row);},
  createCodeBatch(actor,input){requireAction(actor,'create_code');const count=Number(input?.count);if(!Number.isInteger(count)||count<1||count>100)throw new Error('invalid_batch_count');const rows=[];for(let i=0;i<count;i++){let code=`${String(input.prefix||'PISTE').trim().toLocaleUpperCase()}-${String(state.codes.length+1+i).padStart(4,'0')}`;while(state.codes.some(row=>row.code===code))code=`${code}-X`;rows.push(this.createCode(actor,{...input,code,id:undefined}));}return rows;},
  updateCode(actor,id,action,updates={},options={}){requireAction(actor,'manage_codes');const existing=state.codes.find(row=>row.id===id);if(!existing)throw new Error('code_not_found');if(action==='duplicate')return this.createCode(actor,{...existing,...updates,id:undefined,code:updates.code,note:`Copie de ${existing.code}`});const patch=action==='revoked'?{status:'revoked',revoked_at:clock()}:action==='deactivated'?{status:'inactive'}:action==='extended'?{expires_at:updates.expires_at}:action==='activated'?{status:'active'}:null;if(!patch)throw new Error('invalid_code_action');return mutateCode(actor,action,existing,patch,options);},
  codeCatalog(){return Object.freeze({list:()=>clone(state.codes),redeem:(input,{memberId}={})=>{const row=findCode(input);if(!row)return {ok:false,reason:'invalid'};const result=redeemAccessCode(row,input,clock());if(!result.ok)return result;const index=state.codes.findIndex(item=>item.id===row.id);const before=clone(state.codes[index]);state.codes[index]={...result.code,last_used_at:clock()};const member=memberById(memberId);if(member){member.jumolf_entitlement=clone(result.entitlement_record);member.jumolf_enabled=false;member.jumolf_onboarding_completed=false;}state.entitlement_history.push({event_id:`entitlement-${state.entitlement_history.length+1}`,target_id:memberId||null,kind:'jumolf',action:'granted',before:null,after:clone(result.entitlement_record),actor_id:memberId||'member-session',source:'access_code',timestamp:clock()});return {...result,code:clone(state.codes[index]),entitlement_record:clone(result.entitlement_record)};}});},
  removeAdminRole(actor,id,options={}){return this.setAdminRole(actor,id,null,options);}
 });
}
const mFilterKeys={account_status:'account_status'};
