import {escapeHTML as e,StatusBadge} from './components.mjs';
import {PremiumPictogram as P} from './coaching-pictograms.mjs';
import {gpxFixtures} from './track-library.mjs';
import {modes,traceTypes,roleTypes,trackingScenarios,steps,canSeeReference,preparation,validateDraft,referenceLabel} from './coaching.mjs';
const action=(label,value,style='button-gold',extra='')=>`<button class="button ${style}" data-coaching="${value}" ${extra}>${label}</button>`;
const name=(d,id)=>d.participants.find(p=>p.id===id)?.name || 'Non attribué';
const people=(d,role)=>role==='observer'?d.roles.observers:(d.roles[role]?[d.roles[role]]:[]);
const choice=(item,selected,field)=>`<button class="coaching-choice card" data-coaching-choice="${field}" data-value="${e(item.id)}" aria-pressed="${selected===item.id}"><span class="coaching-choice-symbol">${P(item.icon || 'trackPrepared')}</span><span><strong>${e(item.title || item.name)}</strong><small>${e(item.description || item.fileName || item.breed || '')}</small></span><span class="coaching-check" aria-hidden="true">${selected===item.id?'✓':'○'}</span></button>`;
const compactChoice=(item,selected,field,title,description,icon,disabled=false)=>`<button class="coaching-choice coaching-wizard-choice card ${disabled?'is-disabled':''}" data-wizard-option="${field}" data-coaching-choice="${field==='scenario'?'trackingScenario':'traceType'}" data-value="${e(item.id)}" aria-pressed="${selected===item.id}" ${disabled?'disabled':''}><span class="coaching-choice-symbol">${P(icon)}</span><span><strong>${e(title)}</strong><small>${e(description)}</small></span><span class="coaching-check" aria-hidden="true">${selected===item.id?'✓':'○'}</span></button>`;
function summary(d,editable) {
 const rows=[['Mode',modes.find(m=>m.id===d.mode)?.title,'mode'],['Parcours de pose',trackingScenarios.find(s=>s.id===d.trackingScenario)?.title||'Traceur avec application',null],['Type de tracé',traceTypes.find(t=>t.id===d.traceType)?.title,'trace'],...(['prepared','gpx'].includes(d.traceType)?[['Préparation choisie',referenceLabel(d),'prepare']]:[]),['Chien',d.dogs.find(dog=>dog.id===d.dogId)?.name,d.dogs.length===1?null:'dog']];
 const labels={mode:'le mode',trace:'le type de tracé',prepare:'la préparation',dog:'le chien'};
 return `<dl class="coaching-summary">${rows.map(([label,value,step])=>`<div><dt>${label}${P(step==='mode'?'mode':step==='trace'?traceTypes.find(t=>t.id===d.traceType).icon:step==='prepare'?(d.traceType==='gpx'?'gpxImport':'trackPrepared'):'dog','coaching-summary-emblem')}</dt><dd>${e(value)}${editable&&step?`<button class="coaching-edit" data-coaching="edit" data-step="${step}" aria-label="Modifier ${labels[step]}">Modifier</button>`:''}</dd></div>`).join('')}</dl><section class="card coaching-review-roles"><div class="coaching-section-heading"><h2>L’équipe</h2>${editable?'<button class="coaching-edit" data-coaching="edit" data-step="roles" aria-label="Modifier les participants et rôles">Modifier</button>':''}</div>${roleTypes.flatMap(r=>people(d,r.id).map(id=>`<div class="coaching-person-row" data-visual-role="${r.id}">${P(r.icon)}<span><strong>${e(name(d,id))}</strong><small>${r.title}${r.id==='observer'?' · lecture seule':d.creatorRole===r.id?' · votre fonction principale':''}</small></span>${id==='self'?'<span class="badge gold">Vous</span>':''}</div>`)).join('')}</section>`;
}
function visibility(d) {
 if(!d.mode)return '';
 const coachLays=!!d.roles.coach&&d.roles.coach===d.roles.traceur;
 return `<aside class="coaching-visibility"><span class="eyebrow">${P('shield')} VISIBILITÉ DE LA PISTE</span><p>${e(modes.find(m=>m.id===d.mode).visibility)}</p>${d.step==='roles'||d.step==='review'?`<ul>${roleTypes.filter(r=>people(d,r.id).length).map(r=>`<li><span>${r.id==='observer'?`Observateurs (${d.roles.observers.length})`:r.title}</span><strong>${canSeeReference(d.mode,r.id,coachLays)?(r.id==='coach'&&d.mode==='full_blind'&&coachLays?'Connue · Coach poseur':'Visible'):'Masquée'}${r.id==='observer'?' · lecture seule':''}</strong></li>`).join('')}</ul>`:''}</aside>`;
}
function preparationScreen(d,items) {
 if(preparation(d)==='delegated')return `<article class="card coaching-delegated"><span class="coaching-intro-symbol">${P('roleTracer')}</span><h2>Le Traceur fait le choix.</h2><p>Votre fonction ne permet pas de connaître la piste dans ce mode. Le Traceur choisira ${d.traceType==='gpx'?'le fichier GPX':'le tracé préparé'}. Les noms et aperçus restent masqués.</p>${StatusBadge('PRÉPARATION DÉLÉGUÉE')}<p class="coaching-local-note">Vous pourrez ajuster votre fonction à l’étape Participants / rôles.</p></article>`;
 const options=d.traceType==='gpx'?gpxFixtures:items;
 return `<p class="coaching-local-note">${d.traceType==='gpx'?'Choisissez un fichier de démonstration. Aucun fichier lu, aucun parsing GPX.':'Les tracés du Créateur de tracé sont partagés en mémoire avec ce parcours.'}</p><div class="coaching-choices" role="group" aria-label="${d.traceType==='gpx'?'Sélection GPX mock':'Tracé existant'}">${options.map(t=>choice({...t,title:d.traceType==='gpx'?t.fileName:t.name,description:d.traceType==='gpx'?t.name:(t.source==='gpx'?'GPX mock réutilisable':'Tracé mock préparé'),icon:d.traceType==='gpx'?'gpxImport':'trackPrepared'},d.preparationTrack?.id,'preparation')).join('') || '<p class="coaching-local-note">Aucun tracé disponible. Créez un parcours pour le proposer ici.</p>'}</div>${d.traceType==='prepared'?'<a class="button button-dark coaching-builder-link" href="/track-builder">Ouvrir le Créateur de tracé</a>':''}`;
}
function roleCards(d,contacts=[]) {
 const special=d.trackingScenario!=='connected_traceur';
 const contactIds=new Set(contacts.map(person=>person.id));
 const personOptions=(selected)=>`${d.participants.filter(person=>!contactIds.has(person.id)).map(person=>`<option value="${e(person.id)}" ${selected===person.id?'selected':''}>${e(person.name)}${person.id==='self'?' (vous)':''}</option>`).join('')}${contacts.length?`<optgroup label="Mes contacts">${contacts.map(person=>`<option value="${e(person.id)}" ${selected===person.id?'selected':''}>${e(person.displayName||person.name)}</option>`).join('')}</optgroup>`:''}`;
 const people=[...d.participants.filter(person=>!contactIds.has(person.id)),...contacts.map(person=>({id:person.id,name:person.displayName||person.name}))];
 return `${special?`<aside class="coaching-visibility"><p>${d.trackingScenario==='self_trace'?'Vous réaliserez successivement la pose comme Traceur puis la relève comme Conducteur.':'Vous restez le Conducteur connecté. La personne olfactive externe ne reçoit aucune position dans l’application.'}</p></aside>`:`<div class="coaching-principal"><p class="eyebrow">VOTRE FONCTION PRINCIPALE</p><div role="group" aria-label="Votre fonction principale">${roleTypes.filter(r=>r.id!=='observer').map(r=>`<button data-coaching="creator" data-role="${r.id}" aria-pressed="${d.creatorRole===r.id}">${r.title}</button>`).join('')}</div></div><p class="coaching-role-note">Une personne peut exercer plusieurs fonctions successives, si le mode choisi le permet. Les Observateurs restent toujours en lecture seule.</p>`}<div class="coaching-role-list">${roleTypes.filter(r=>r.id!=='observer').map(r=>`<article class="card coaching-role" data-visual-role="${r.id}"><div class="coaching-role-title">${P(r.icon)}<div><h2>${r.title}</h2><p>${r.description}</p></div></div>${special&&r.id==='traceur'?`<p>${d.trackingScenario==='self_trace'?'Vous · pose réalisée avec le rôle Traceur':'Traceur externe · sans compte ni position dans l’application'}</p>`:special&&r.id==='driver'?`<p>Vous · Conducteur connecté</p>`:`<label for="coaching-${r.id}">${r.id==='driver'?`Qui travaille avec ${e(d.dogs.find(dog=>dog.id===d.dogId)?.name || 'le chien')} ?`:r.id==='traceur'?'Qui prépare la piste ?':'Qui accompagne le binôme ?'}</label><select id="coaching-${r.id}" data-coaching-role="${r.id}"><option value="">${r.id==='coach'?'Sans coach':r.id==='traceur'?'À définir':'Choisir un conducteur'}</option>${personOptions(d.roles[r.id])}</select>`}</article>`).join('')}<article class="card coaching-role" data-visual-role="observer"><div class="coaching-role-title">${P('roleObserver')}<div><h2>Observateurs</h2><p>Lecture seule totale. Aucun contrôle, aucune modification.</p></div></div><fieldset class="observer-options"><legend>Choisir les Observateurs · ${d.roles.observers.length} sélectionné(s)</legend>${people.filter(p=>!special||p.id!=='self').map(p=>`<label class="observer-pick"><input type="checkbox" data-coaching-observer="${e(p.id)}" ${d.roles.observers.includes(p.id)?'checked':''}><span>${e(p.name)}${p.id==='self'?' (vous)':''}</span></label>`).join('')}</fieldset></article></div>${visibility(d)}`;
}
export function CoachingScreen(d,feedback='',items=[],contacts=[],livePolicy={}) {
 if(d.session)return `<section class="coaching-flow" data-visual-mode="${e(d.mode || '')}"><div class="coaching-success-symbol">${P('check')}</div><span class="eyebrow">VOTRE PROCHAINE PISTE</span><h1>Votre session est prête.</h1><p class="coaching-lead">Un objectif commun. Un binôme prêt à progresser.</p><section class="card session-code-card"><label class="eyebrow" for="session-code">CODE SESSION MOCK</label><input id="session-code" readonly value="${e(d.session.code)}" aria-label="Code session mock"><div class="coaching-actions">${action('Copier','copy-code','button-dark')}${action('Partager','share')}</div><p data-copy-status role="status" class="coaching-local-note">Un code pour réunir votre équipe. Le lien d’invitation associé est un aperçu.</p></section><section class="card live-policy-controls" data-live-policy-session="${e(d.session.id)}" data-session-type="coaching"><span class="eyebrow">PARTAGE LIVE · COACHING</span><label><input type="checkbox" data-live-policy="share_live" data-session-id="${e(d.session.id)}" data-session-type="coaching" ${livePolicy.share_live?'checked':''}>Partager cette session avec mes observateurs autorisés</label><small>Seuls les Contacts autorisés à l’accès Live peuvent consulter cette session en Observateur.</small><label><input type="checkbox" data-live-policy="notify_observers" data-session-id="${e(d.session.id)}" data-session-type="coaching" ${livePolicy.notify_observers!==false?'checked':''}>Prévenir mes observateurs autorisés</label></section><p class="coaching-local-note">Création simulée, conservée uniquement dans cet aperçu. Recharger efface cette session. Aucun participant n’est invité.</p>${summary(d,false)}${visibility(d)}<a class="button button-gold coaching-preparation-entry" href="/coaching/session">Ouvrir la préparation</a><div class="coaching-actions">${action('Créer une autre session','restart','button-dark')}<a class="button button-gold" href="/">Retour à l’accueil</a></div></section>`;
 const sequence=steps(d),index=sequence.indexOf(d.step),total=sequence.length-1;
 const headings={intro:'Créer une session',mode:'Quel mode pour votre session ?',scenario:'Qui réalise la pose ?',trace:'Comment préparer la piste ?',prepare:d.traceType==='gpx'?'Choisir un GPX mock':'Choisir un tracé préparé',dog:'Avec quel chien ?',roles:'Votre équipe sur le terrain',review:'Prêts à créer la session ?'};
 const descriptions={mode:'Choisissez ce que chacun connaît de la piste.',scenario:'Choisissez qui réalise et, si besoin, enregistre la pose.',trace:'Choisissez comment préparer la piste.',dog:'Choisissez le binôme qui participera à l’exercice.',roles:'Des fonctions claires, un objectif partagé.',review:'Vérifiez votre binôme et l’organisation de l’exercice.'};
 let content='';
 if(d.step==='intro')content=`<div class="coaching-intro card"><span class="coaching-intro-symbol">${P('mode')}</span><span class="eyebrow">ENTRAÎNEMENT · COACHING · ÉVALUATION</span><h2>Chaque piste est une occasion de progresser.</h2><p>Le Coach aide à fixer un objectif, observer votre binôme et transformer le débrief en progrès concrets. Préparez ensemble un entraînement ou une évaluation.</p><div class="coaching-value"><span>${P('roleCoach')} Un regard extérieur</span><span>${P('roleDriver')} Un binôme mieux compris</span><span>${P('analysis')} Des progrès concrets</span></div></div><div class="card coaching-dog-inline">${P('dog')}<span><strong>${e(d.dogs.length===1?d.dogs[0].name:'Votre binôme')}</strong><small>${d.dogs.length===1?'Votre chien est déjà sélectionné.':'Vous choisirez votre chien pendant la préparation.'}</small></span>${StatusBadge(d.dogs.length===1?'PRÊT':'À CHOISIR')}</div>${action('Commencer','next')}<p class="coaching-local-note">Un aperçu avec des participants fictifs. Rien n’est enregistré hors de cette page.</p>`;
 if(d.step==='mode'){const selectedScenario=trackingScenarios.find(s=>s.id===d.trackingScenario);content=`<div class="coaching-choices" role="group" aria-label="Mode de session">${modes.map(m=>`<button class="coaching-choice card ${selectedScenario?.normalOnly&&m.id!=='normal'?'is-disabled':''}" data-coaching-choice="mode" data-value="${e(m.id)}" aria-pressed="${d.mode===m.id}" ${selectedScenario?.normalOnly&&m.id!=='normal'?'disabled':''}><span class="coaching-choice-symbol">${P(m.icon)}</span><span><strong>${e(m.title)}</strong><small>${e(m.description)}</small></span><span class="coaching-check" aria-hidden="true">${d.mode===m.id?'✓':'○'}</span></button>`).join('')}</div>${selectedScenario?.normalOnly?'<p class="coaching-local-note" role="status">Ce parcours nécessite le mode Normal : la même personne connaît la piste qu’elle vient de poser.</p>':''}${visibility(d)}`;}
 if(d.step==='scenario')content=`<div class="coaching-choices" role="group" aria-label="Qui réalise la pose ?">${trackingScenarios.map((s,i)=>compactChoice(s,d.trackingScenario,'scenario',['Traceur avec application','Je trace pour moi-même','Traceur externe','Traceur externe + enregistrement'][i],['Il réalise et enregistre la pose.','Pose puis relève avec le même téléphone.','Sans application ni localisation.','Vous enregistrez sa pose avec votre téléphone.'][i],['roleTracer','roleDriver','roleTracer','roleDriver'][i],s.normalOnly&&d.mode!=='normal')).join('')}</div>`;
 if(d.step==='trace')content=`<div class="coaching-choices" role="group" aria-label="Comment préparer la piste ?">${traceTypes.map((t,i)=>compactChoice(t,d.traceType,'preparation',['Terrain direct','Tracé préparé','Import GPX','Sans tracé préparé'][i],['La piste sera définie directement sur le terrain.','Choisir une piste enregistrée à l’avance.','Utiliser un fichier GPX.','Définir la piste plus tard.'][i],t.icon)).join('')}</div>`;
 if(d.step==='prepare')content=preparationScreen(d,items);
 if(d.step==='dog')content=`<div class="coaching-choices" role="group" aria-label="Choisir un chien">${d.dogs.map(dog=>choice({...dog,icon:'dog'},d.dogId,'dogId')).join('')}</div>`;
 if(d.step==='roles')content=roleCards(d,contacts);
 if(d.step==='review')content=`${summary(d,true)}${visibility(d)}<div class="coaching-preparation card"><span class="eyebrow">PRÉPARATION</span><p>${preparation(d)==='delegated'?'Le choix et la préparation restent réservés au Traceur. Votre fonction ne permet pas de consulter cette piste.':preparation(d)==='later'?'La piste sera définie plus tard. Vous pouvez déjà organiser votre équipe.':'Votre choix mock est prêt pour cet exercice. Aucune piste réelle n’est créée.'}</p></div><p class="coaching-local-note">Cette création est simulée. Aucune invitation ne sera envoyée.</p>`;
 const errors=d.step==='roles'||d.step==='review'?validateDraft(d):[];
 const canContinue=d.step==='mode'?!!d.mode:d.step==='scenario'?!!d.trackingScenario:d.step==='trace'?!!d.traceType:d.step==='prepare'?preparation(d)==='delegated'||!!d.preparationTrack:d.step==='dog'?!!d.dogId:errors.length===0;
 return `<section class="coaching-flow" data-wizard-step="${e(d.step)}" data-visual-mode="${e(d.mode || '')}"><a class="back-link" href="/">← Accueil</a>${d.step!=='intro'?`<div class="coaching-progress"><span>CRÉER UNE SESSION</span><span>Étape ${index} / ${total}</span><progress aria-label="Préparation de la session" max="${total}" value="${index}"></progress></div>`:''}<header class="coaching-heading"><span class="eyebrow">COACHING SUR LE TERRAIN</span><h1>${headings[d.step]}</h1>${d.mode&&d.step!=='intro'?`<span class="badge coaching-mode-reminder">${e(modes.find(m=>m.id===d.mode)?.title || '')}</span>`:''}${descriptions[d.step]?`<p>${descriptions[d.step]}</p>`:''}</header>${content}${errors.length?`<div class="coaching-errors" role="alert">${errors.map(error=>`<p>${e(error.message)}</p>`).join('')}${errors.some(error=>error.code==='preparation_required')?action('Choisir le tracé','edit','button-dark','data-step="prepare"'):''}</div>`:''}${feedback?`<p role="alert">${e(feedback)}</p>`:''}${d.step!=='intro'?`<div class="coaching-actions">${action('Retour','back','button-dark')}${action(d.step==='review'?'Créer la session':d.editing?'Revenir au récapitulatif':'Continuer',d.step==='review'?'create':'next',d.step==='review'?'button-gold':'button-gold',canContinue?'':'disabled')}</div>`:''}</section>`;
}
