import {escapeHTML as e,StatusBadge,EmptyState} from './components.mjs';
import {DogPhotoMarkup} from './dogs-screen.mjs';
import {dogDisciplines} from './dogs.mjs';
import {COMMUNITY_PHOTO_FIXTURES} from './community-fixtures.mjs';
import {COMMUNITY_SHARE_FIELDS,searchCommunity} from './community-model.mjs';

const fieldLabels=Object.freeze({dog:'Chien',distance:'Distance',trackAge:'Âge de piste',environment:'Environnement',difficulty:'Difficulté',result:'Résultat',map:'Carte / tracé',points:'Points du tracé',provenance:'Provenance'});
const typeLabels=Object.freeze({training:'Entraînement',session:'Session terminée',track:'Piste partagée',photo:'Photo terrain',technical:'Contenu technique','field-note':'Retour terrain'});
const visibilityLabels=Object.freeze({private:'Privé',contacts:'Contacts',community:'Communauté'});
const dogUrl=id=>`/dogs/${encodeURIComponent(id)}`;
const htmlButton=(action,label,attrs='')=>`<button type="button" class="button button-subtle" data-community-action="${e(action)}" ${attrs}>${e(label)}</button>`;
function profileLink(person){return `<a class="community-author" href="/community/profile/${encodeURIComponent(person.id)}"><span class="community-avatar" aria-hidden="true">${e((person.displayName||'?').trim().slice(0,1).toLocaleUpperCase('fr'))}</span><span><strong>${e(person.displayName||'Membre')}</strong><small>${e(person.role||person.specialty||'Membre Communauté')}</small></span></a>`;}
function formatDate(value){const date=new Date(value);return Number.isFinite(date.getTime())?new Intl.DateTimeFormat('fr-FR',{day:'numeric',month:'short',year:'numeric'}).format(date):'Date indisponible';}
function selectedDog(dogs,id){return dogs.find(item=>item.id===id)||null;}
function dogCard(dog){
 const labels=dogDisciplines(dog).map(id=>({tracking:'Piste',defense:'Défense',search:'Recherche',narcotics:'Stupéfiants',other:'Autre'}[id]||id));
 return `<a class="community-dog-card" href="${dogUrl(dog.id)}">${DogPhotoMarkup(dog,'community-dog-photo')}<span><strong>${e(dog.name)}</strong><small>${e(labels.length?labels.join(' · '):'Discipline indisponible')}</small></span></a>`;
}
function visibilityBadge(value){return `<span class="community-visibility">${e(visibilityLabels[value]||'Visibilité indisponible')}</span>`;}
function attachmentMarkup(attachment){
 if(!attachment?.fields)return '';
 const fields=attachment.fields,entries=[];
 for(const field of COMMUNITY_SHARE_FIELDS){const value=fields[field];if(value===undefined)continue;if(field==='dog')entries.push(`<span><b>Chien</b> · ${e(value.name||'Aucune donnée disponible')}</span>`);else if(field!=='map'&&field!=='points')entries.push(`<span><b>${e(fieldLabels[field]||field)}</b> · ${e(String(value))}</span>`);}
 let trace='';
 if(fields.map?.paths?.length){trace=fields.map.paths.map(path=>`<path d="${e(path.d)}"></path>`).join('');}
 else if(fields.points?.length>1){const groups=[];for(const point of fields.points){if(!groups.length||point.breakBefore)groups.push([]);groups.at(-1).push(point);}trace=groups.filter(group=>group.length>1).map(group=>`<path d="${group.map((point,index)=>`${index?'L':'M'} ${point.x} ${point.y}`).join(' ')}"></path>`).join('');}
 const map=trace?`<svg class="community-trace-map" viewBox="0 0 360 260" role="img" aria-label="Aperçu de tracé partagé en lecture seule"><path class="community-map-grid" d="M0 65h360M0 130h360M0 195h360M90 0v260M180 0v260M270 0v260"></path><g>${trace}</g></svg>`:'';
 if(!entries.length&&!map)return '';
 return `<section class="community-attachment" aria-label="Données choisies pour le partage"><div class="community-attachment-copy">${entries.join('')}</div>${map}<small>Lecture seule · données explicitement partagées</small></section>`;
}
function postCard(post,store,dogs,{detail=false,shareMode='post'}={}){
 const state=store.getState(),person=store.getProfile(post.authorId)||{id:post.authorId,displayName:'Membre'},dog=selectedDog(dogs,post.dogId),liked=post.likes.includes(store.viewerId);
 const comments=detail?post.comments.map(comment=>{const author=store.getProfile(comment.authorId)||{displayName:'Membre'};return `<li>${profileLink(author)}<p>${e(comment.text)}</p>${comment.authorId===store.viewerId?htmlButton('delete-comment','Supprimer',`data-post-id="${e(post.id)}" data-comment-id="${e(comment.id)}"`):''}</li>`;}).join(''):'';
 const photo=post.photo?`<img class="community-post-photo" src="${e(post.photo)}" alt="Photo terrain partagée" loading="lazy">`:'';
 const text=post.text?`<p class="community-post-text">${e(post.text)}</p>`:'';
 const body=`${photo}${text}${dog?dogCard(dog):''}${attachmentMarkup(post.attachment)}`;
 const menu=`<details class="community-post-menu"><summary aria-label="Actions de modération">···</summary><div>${htmlButton('report-post','Signaler',`data-post-id="${e(post.id)}"`)}${htmlButton('hide-post','Masquer',`data-post-id="${e(post.id)}"`)}${post.authorId===store.viewerId?htmlButton('delete-post','Supprimer ma publication',`data-post-id="${e(post.id)}"`):''}</div></details>`;
 const actions=`<div class="community-post-actions">${htmlButton('like',liked?'Ne plus aimer':'J’aime',`data-post-id="${e(post.id)}" aria-pressed="${liked}"`)}<span class="community-like-count">${post.likes.length} J’aime</span><a class="community-comment-link" href="/community/post/${encodeURIComponent(post.id)}">${post.comments.length} commentaire${post.comments.length===1?'':'s'}</a><button type="button" class="button button-subtle" data-community-action="share-post" data-post-id="${e(post.id)}">Partager la publication</button>${post.attachment?.type==='track'?`<button type="button" class="button button-subtle" data-community-action="share-track" data-post-id="${e(post.id)}">Partager la piste</button>`:''}</div>`;
 const commentBlock=detail?`<section class="community-comments"><h2>Commentaires <span>${post.comments.length}</span></h2>${comments?`<ul>${comments}</ul>`:EmptyState('Pas encore de commentaire','Les retours publiés apparaîtront ici.','users')}<form data-community-form="comment" data-post-id="${e(post.id)}"><label for="community-comment-${e(post.id)}">Ajouter un commentaire</label><textarea id="community-comment-${e(post.id)}" name="text" maxlength="600" required></textarea><button class="button button-gold" type="submit">Publier le commentaire</button></form></section>`:'';
 return `<article class="community-post-card" data-community-post="${e(post.id)}" data-visibility="${e(post.visibility)}"><header>${profileLink(person)}<div class="community-post-meta"><span>${e(typeLabels[post.type]||'Publication')}</span>${visibilityBadge(post.visibility)}<time datetime="${e(post.createdAt||'')}">${e(formatDate(post.createdAt))}</time></div>${menu}</header><div class="community-post-body">${body}</div>${actions}${commentBlock}</article>`;
}
function relationActions(store,targetId){
 const relation=store.getRelation(targetId);if(relation.isSelf)return '';
 const contact=relation.contactStatus;
 let contactUI='';
 if(contact==='none')contactUI=htmlButton('contact-request','Ajouter aux contacts',`data-user-id="${e(targetId)}"`);
 else if(contact==='outgoing_pending')contactUI=`<span class="community-relation-state">Demande envoyée</span>${htmlButton('cancel-contact','Annuler la demande',`data-user-id="${e(targetId)}"` )}`;
 else if(contact==='incoming_pending')contactUI=`<span class="community-relation-state">Demande reçue</span>${htmlButton('accept-contact','Accepter',`data-user-id="${e(targetId)}"`)}${htmlButton('refuse-contact','Refuser',`data-user-id="${e(targetId)}"` )}`;
 else contactUI=`<span class="community-relation-state">Contact</span>${htmlButton('remove-contact','Retirer de mes contacts',`data-user-id="${e(targetId)}"` )}`;
 return `<div class="community-social-actions">${htmlButton(relation.following?'unfollow':'follow',relation.following?'Ne plus suivre':'Suivre',`data-user-id="${e(targetId)}" aria-pressed="${relation.following}"`)}<div class="community-contact-actions">${contactUI}</div></div>`;
}
function contactPermissionControls(store,targetId){
 const permissions=store.getContactPermissions(targetId);if(!permissions)return '';
 return `<fieldset class="community-contact-permissions"><legend>Accès accordés à ce contact</legend><label><input type="checkbox" data-community-permission="live_access_authorized" data-user-id="${e(targetId)}" ${permissions.live_access_authorized?'checked':''}><span><strong>Autoriser l’accès Live</strong><small>Ce contact pourra voir vos sessions que vous choisissez de partager en Live, sans invitation individuelle à chaque fois.</small></span></label><label><input type="checkbox" data-community-permission="quick_coaching_invite_authorized" data-user-id="${e(targetId)}" ${permissions.quick_coaching_invite_authorized?'checked':''}><span><strong>Retrouver dans Coaching</strong><small>Ce réglage facilite l’invitation; il ne donne aucun rôle Coaching.</small></span></label></fieldset>`;
}
function pageHeader(kicker,title,description,actions=''){
 return `<header class="community-heading"><span class="eyebrow">${e(kicker)}</span><div><h1>${e(title)}</h1>${actions}</div><p>${e(description)}</p></header>`;
}
function profileScreen(route,store,dogs){
 const person=store.getProfile(route.id);if(!person)return `<section class="community-page community-profile-page">${EmptyState('Profil indisponible','Ce profil n’est pas disponible dans cette visite mock.','users')}<a class="button button-dark" href="/community">Retour au fil</a></section>`;
 const own=person.id===store.viewerId,ownDogs=(person.dogIds||[]).map(id=>selectedDog(dogs,id)).filter(Boolean),posts=store.getFeed().filter(post=>post.authorId===person.id),relation=store.getRelation(person.id);
 const actions=own?`<a class="button button-subtle" href="/community/contacts">Gérer mes contacts</a>`:relationActions(store,person.id)+contactPermissionControls(store,person.id);
 const edit=own?`<form class="community-profile-edit" data-community-form="profile"><label for="community-display-name">Nom visible</label><input id="community-display-name" name="displayName" maxlength="80" required value="${e(person.displayName)}"><button type="submit" class="button button-gold">Enregistrer mon nom visible</button></form>`:'';
 const dogSection=ownDogs.length?`<section class="community-section"><h2>Chiens liés</h2><div class="community-dog-grid">${ownDogs.map(dogCard).join('')}</div></section>`:EmptyState('Aucun chien visible','Aucun chien n’est lié à ce profil Communauté.','dog');
 const state=store.getState(),contactCount=state.contacts.filter(item=>item.userIds?.includes(person.id)).length;
 const stats=(person.publicStats||[]).map(item=>`<div><strong>${e(item.value)}</strong><span>${e(item.label)}</span></div>`).join('');
 return `<section class="community-page community-profile-page" data-community-route="profile" data-profile-id="${e(person.id)}"><a class="back-link" href="/community">← Communauté</a>${pageHeader(own?'MON PROFIL':'PROFIL COMMUNAUTÉ',person.displayName,person.bio||'Aucune biographie disponible.',actions)}<article class="community-profile-card"><div class="community-profile-identity"><span class="community-avatar community-avatar-large" aria-hidden="true">${e(person.displayName.slice(0,1).toLocaleUpperCase('fr'))}</span><div><h2>${e(person.role||'Rôle indisponible')}</h2><p>${e(person.specialty||'Spécialité indisponible')} · ${e(person.location||'Localisation non renseignée')}</p></div></div>${edit}<div class="community-profile-tags">${(person.disciplines||[]).map(label=>`<span>${e(label)}</span>`).join('')}</div><div class="community-profile-stats"><div><strong>${posts.length}</strong><span>Publications visibles</span></div><div><strong>${contactCount}</strong><span>Contacts</span></div><div><strong>${state.follows.filter(item=>item.toUserId===person.id).length}</strong><span>Abonnés</span></div><div><strong>${state.follows.filter(item=>item.fromUserId===person.id).length}</strong><span>Abonnements</span></div>${stats}</div></article>${dogSection}<section class="community-section"><h2>Publications <span>${posts.length}</span></h2>${posts.length?posts.map(post=>postCard(post,store,dogs)).join(''):EmptyState('Aucune publication visible','Les publications partagées par ce profil apparaîtront ici.','users')}</section></section>`;
}
function contactsScreen(store,query=''){
 const requests=store.getContactRequests(),profiles=store.listProfiles(),person=id=>store.getProfile(id);
 const card=(profile,kind)=>`<article class="community-person-row" data-community-person="${e(profile.id)}">${profileLink(profile)}<div class="community-person-actions">${relationActions(store,profile.id)}${kind==='contact'?contactPermissionControls(store,profile.id):''}</div></article>`;
 const contacts=requests.contacts.map(item=>card(item,'contact')).join('');
 const received=requests.received.map(item=>card(person(item.fromUserId),'received')).join('');
 const sent=requests.sent.map(item=>card(person(item.toUserId),'sent')).join('');
 const known=new Set([...requests.contacts.map(item=>item.id),...requests.received.map(item=>item.fromUserId),...requests.sent.map(item=>item.toUserId)]);
 const suggestions=profiles.filter(item=>item.id!==store.viewerId&&!known.has(item.id)).map(item=>card(item,'suggestion')).join('');
 const results=query?store.searchContacts(query):[];
 const search=`<section class="community-section community-contact-search"><details ${query?'open':''}><summary class="button button-gold">+ Ajouter un contact</summary><form data-community-form="contact-search"><label for="community-contact-query">Rechercher par nom ou rôle</label><input id="community-contact-query" type="search" name="q" value="${e(query)}" placeholder="Nom, rôle ou spécialité"><button class="button button-gold" type="submit">Rechercher</button></form>${query?`<div class="community-contact-results" aria-live="polite">${results.length?results.map(item=>card(item,'search')).join(''):EmptyState('Aucun membre correspondant','Essayez un nom ou une spécialité différente.','search')}</div>`:''}</details></section>`;
 return `<section class="community-page community-contacts-page" data-community-route="contacts"><a class="back-link" href="/community">← Communauté</a>${pageHeader('RELATIONS','Contacts','Gérez les relations réciproques et les demandes, séparément de vos abonnements.')}${search}<section class="community-section"><h2>Mes contacts <span>${requests.contacts.length}</span></h2>${contacts||EmptyState('Aucun contact pour le moment','Acceptez une demande pour créer une relation réciproque.','users')}</section><section class="community-section"><h2>Demandes reçues <span>${requests.received.length}</span></h2>${received||EmptyState('Aucune demande reçue','Les nouvelles demandes apparaîtront ici.','users')}</section><section class="community-section"><h2>Demandes envoyées <span>${requests.sent.length}</span></h2>${sent||EmptyState('Aucune demande en attente','Les demandes envoyées apparaîtront ici.','users')}</section><section class="community-section"><h2>Suggestions <span>${profiles.filter(item=>item.id!==store.viewerId&&!known.has(item.id)).length}</span></h2>${suggestions||EmptyState('Aucune suggestion disponible','Revenez plus tard pour découvrir des membres.','users')}</section></section>`;
}
 function sourceFields(source){
 const available=new Set(source?.availableFields||[]);
 return COMMUNITY_SHARE_FIELDS.filter(field=>available.has(field)).map(field=>`<label class="community-field-choice"><input type="checkbox" form="community-post-create-form" name="shareFields" value="${e(field)}"><span><strong>${e(fieldLabels[field])}</strong><small>${e(source.data?.[field]?.name||source.data?.[field]||'Ce champ sera inclus seulement si vous le cochez.')}</small></span></label>`).join('');
}
function newPostScreen({store,dogs,source,sourceOptions=[]}){
 const own=store.getProfile(store.viewerId),linkedDogs=(own?.dogIds||[]).map(id=>selectedDog(dogs,id)).filter(Boolean);
 const options=sourceOptions.map(item=>`<option value="${e(item.type)}:${e(item.id)}"${source?.type===item.type&&source.id===item.id?' selected':''}>${e(item.type==='session'?'Session · ':'Piste · ')}${e(item.label)}</option>`).join('');
 const sourceUI=source?.blocked?`<div class="community-source-blocked">${e(source.reason||'Cette source ne peut pas être partagée dans Communauté.')}</div>`:source?`<section class="community-source-picker"><label for="community-source-select">Élément à partager</label><select id="community-source-select" data-community-source-picker><option value="">Publication libre</option>${options}</select><p data-community-source-label>${e(source.label)}</p>${source.availableFields?.length?`<fieldset class="community-field-options"><legend>Choisir les informations exposées</legend>${sourceFields(source)}</fieldset>`:'<p>Aucune donnée partageable disponible pour cet élément.</p>'}</section>`:`<section class="community-source-picker"><label for="community-source-select">Élément à partager <span>facultatif</span></label><select id="community-source-select" data-community-source-picker><option value="">Publication libre</option>${options}</select><p>Choisissez une session terminée ou une piste ; aucun champ ne sera partagé par défaut.</p></section>`;
 const visibility=Object.entries(visibilityLabels).map(([value,label])=>`<label class="community-visibility-choice"><input type="radio" name="visibility" value="${value}"${value==='private'?' checked':''}><span><strong>${e(label)}</strong><small>${value==='private'?'Visible par vous uniquement.':value==='contacts'?'Visible uniquement par vos contacts acceptés.':'Visible dans le fil Communauté.'}</small></span></label>`).join('');
 return `<section class="community-page community-new-page" data-community-route="new"><a class="back-link" href="/community">← Communauté</a>${pageHeader('NOUVELLE PUBLICATION','Partager une expérience','Prévisualisez les informations et choisissez leur visibilité avant de publier.')}${sourceUI}<form id="community-post-create-form" class="community-composer" data-community-form="post-create" data-source-type="${e(source?.type||'')}" data-source-id="${e(source?.id||'')}"><label for="community-post-text">Votre retour terrain</label><textarea id="community-post-text" name="text" maxlength="1200" placeholder="Racontez ce que vous souhaitez partager."></textarea><label for="community-post-dog">Chien <span>facultatif</span></label><select id="community-post-dog" name="dogId"><option value="">Ne pas associer de chien</option>${linkedDogs.map(dog=>`<option value="${e(dog.id)}">${e(dog.name)}</option>`).join('')}</select><label for="community-post-photo">Photo mock locale <span>facultatif</span></label><select id="community-post-photo" name="photo"><option value="">Aucune photo</option>${COMMUNITY_PHOTO_FIXTURES.map(photo=>`<option value="${e(photo.src)}">${e(photo.label)}</option>`).join('')}</select><fieldset class="community-visibility-options"><legend>Qui peut voir cette publication ?</legend>${visibility}</fieldset><section class="community-post-preview" aria-live="polite"><span class="eyebrow">APERÇU</span><p data-community-preview-text>Seuls le texte, le chien, la photo et les champs cochés ci-dessus seront publiés.</p><div data-community-preview-fields>Aucune donnée de session ou de piste sélectionnée.</div></section><button class="button button-gold" type="submit">Prévisualiser et continuer</button><p class="community-local-note">Publication mock en mémoire pour cette visite. Rien n’est envoyé automatiquement.</p><dialog class="community-confirm-dialog" data-community-confirm-dialog><h2>Confirmer la publication</h2><p data-community-confirm-description>Vérifiez le contenu et sa visibilité avant de publier.</p><button class="button button-subtle" type="button" data-community-action="cancel-post">Retour à l’aperçu</button><button class="button button-gold" type="button" data-community-action="confirm-post">Publier maintenant</button></dialog></form></section>`;
}
function searchScreen({store,dogs,tracks,query}){
 const results=searchCommunity({state:store.getState(),viewerId:store.viewerId,query,dogs,tracks});
 const items=results.map(result=>{
  if(result.type==='profile'){const person=store.getProfile(result.id);return `<article class="community-search-result" data-community-result="profile">${profileLink(person)}${relationActions(store,result.id)}</article>`;}
  const href=result.type==='dog'?dogUrl(result.id):result.type==='track'?`/community/post/${encodeURIComponent(result.id)}?share=track`:result.type==='post'?`/community/post/${encodeURIComponent(result.id)}`:'#';
  return `<a class="community-search-result" data-community-result="${e(result.type)}" href="${href}"><strong>${e(result.title)}</strong><small>${e(result.subtitle)}</small></a>`;
 }).join('');
 return `<section class="community-page community-search-page" data-community-route="search"><a class="back-link" href="/community">← Communauté</a>${pageHeader('DÉCOUVERTE','Rechercher','Membres, chiens, disciplines, publications et pistes partagées.') }<form class="community-search-form" data-community-form="search"><label for="community-search-query">Rechercher dans Communauté</label><input id="community-search-query" type="search" name="q" value="${e(query)}" placeholder="Nom, chien, discipline, piste…"><button class="button button-gold" type="submit">Rechercher</button></form><section class="community-search-results" aria-live="polite">${items||EmptyState(query?'Aucun résultat visible':'Lancez une recherche','Seuls les contenus visibles pour votre compte sont proposés.','search')}</section></section>`;
}
function feedScreen(store,dogs){
 const posts=store.getFeed(),notifications=store.getNotifications();
 const actions=`<nav class="community-header-actions" aria-label="Actions Communauté"><a class="button button-subtle" href="/community/profile/me">Mon profil</a><a class="button button-subtle" href="/community/search">Découvrir</a><a class="button button-subtle" href="/community/contacts">Contacts <span>${store.getContactRequests().contacts.length}</span></a><a class="button button-gold" href="/community/new">Nouvelle publication</a></nav>`;
 const notificationItems=notifications.map(item=>`<li>${e(item.type==='contact_request'?'Nouvelle demande de contact':item.type==='contact_accepted'?'Demande de contact acceptée':item.type==='follow'?'Nouvel abonnement':item.type==='like'?'Nouveau J’aime':'Nouveau commentaire')}</li>`).join('');
 return `<section class="community-page community-feed-page" data-community-route="feed">${pageHeader('PISTAGE · CHIENS · TERRAIN','Communauté','Des retours de terrain, des chiens et des traces partagées avec maîtrise.',actions)}<details class="community-notifications"><summary>Notifications <span>${notifications.length}</span></summary>${notificationItems?`<ul>${notificationItems}</ul>`:EmptyState('Aucune notification','Les nouvelles interactions apparaîtront ici.','users')}</details><section class="community-feed" aria-label="Fil communautaire">${posts.length?posts.map(post=>postCard(post,store,dogs)).join(''):EmptyState('Le fil est calme','Les publications visibles apparaîtront ici.','users')}</section></section>`;
}
function postScreen(route,store,dogs,shareMode){
 const post=store.getVisiblePost(route.id);if(!post)return `<section class="community-page community-post-detail" data-community-route="post">${EmptyState('Publication indisponible','Elle est privée ou n’est pas disponible pour ce profil.','users')}<a class="button button-dark" href="/community">Retour au fil</a></section>`;
 return `<section class="community-page community-post-detail" data-community-route="post" data-share-mode="${shareMode==='track'?'track':'post'}"><a class="back-link" href="/community">← Communauté</a>${pageHeader(shareMode==='track'?'PISTE PARTAGÉE · LECTURE SEULE':'PUBLICATION COMMUNAUTÉ','Retour de terrain','Contenu mock · les données visibles sont celles choisies par l’auteur.')}${postCard(post,store,dogs,{detail:true,shareMode})}</section>`;
}

export function CommunityScreen({route,store,dogs=[],tracks=[],source=null,sourceOptions=[],query='',shareMode='post'}={}){
 if(!route||!store)return '<section class="community-page"><h1>Communauté indisponible</h1></section>';
 if(route.type==='feed')return feedScreen(store,dogs);
 if(route.type==='profile')return profileScreen(route,store,dogs);
 if(route.type==='contacts')return contactsScreen(store,query);
 if(route.type==='new')return newPostScreen({store,dogs,source,sourceOptions});
 if(route.type==='search')return searchScreen({store,dogs,tracks,query});
 if(route.type==='post')return postScreen(route,store,dogs,shareMode);
 return `<section class="community-page">${EmptyState('Page Communauté indisponible','Cette route n’existe pas.','users')}<a class="button button-dark" href="/community">Retour au fil</a></section>`;
}
