import { Icon } from './icons.mjs';
export const escapeHTML = (value='') => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const e = escapeHTML;
export function StatusBadge(label, tone='gold') { return `<span class="badge ${e(tone)}">${e(label)}</span>`; }
export function PremiumCard(content, className='') { return `<article class="card ${e(className)}">${content}</article>`; }
export function SectionTitle(title, extra='') { return `<div class="section-title"><h2>${e(title)}</h2>${extra}</div>`; }
export function ScreenHeader(name, initials=name.slice(0,1), home=false, unreadCount=0) { return `<header class="screen-header"><a class="brand" href="/" aria-label="PISTE Community, accueil">${home ? '<span class="home-welcome-logo" aria-hidden="true"></span>' : `${Icon('premiumBrandDog')}<span>PISTE<small>COMMUNITY</small></span>`}</a><div class="header-actions"><a class="icon-button notification" href="/notifications" aria-label="${unreadCount?`Notifications, ${e(unreadCount)} non lues`:'Notifications'}">${Icon('bell')}${unreadCount?`<span class="notification-count" aria-label="${e(unreadCount)} non lues">${e(unreadCount)}</span>`:'<span class="notification-dot" aria-hidden="true"></span>'}</a><a href="/profile" class="avatar" aria-label="Profil de ${e(name)}">${e(initials)}</a></div></header>`; }
const nav = [['/','navHome','Accueil'],['/dogs','premiumBrandDog','Chiens'],['/live','navLive','Live'],['/sessions','navSessions','Sessions'],['/profile','navProfile','Profil']];
export function BottomNavigation(route) { return `<nav class="bottom-nav" aria-label="Navigation principale">${nav.map(([href,icon,label])=>{const active=route===href||(href!=='/'&&route.startsWith(`${href}/`))||(href==='/sessions'&&['/tracks','/track-builder'].some(root=>route===root||route.startsWith(`${root}/`)));return `<a href="${href}" ${active?'aria-current="page"':''}>${Icon(icon,'navigation-icon')}<span>${label}</span></a>`;}).join('')}</nav>`; }
export function AppShell(content, route, name, initials, theme='base', unreadCount=0) { const cockpit=content.includes('operational-cockpit-page'),jumolf=String(route||'').startsWith('/jumolf'),notifications=String(route||'').startsWith('/notifications'),scientific=String(route||'').startsWith('/scientific'),admin=String(route||'').startsWith('/admin'); return `<div class="app-shell ${route==='/'?'home-shell':''}${cockpit?' operational-cockpit-shell':''}${notifications?' notifications-shell':''}${scientific?' scientific-layout':''}${admin?' admin-layout-shell':''}" data-module-theme="${e(theme)}"${jumolf?' data-jumolf="true"':''}><a class="skip-link" href="#main">Aller au contenu</a>${ScreenHeader(name,initials,route==='/',unreadCount)}<main id="main" tabindex="-1">${content}<footer class="prototype-note">PISTE COMMUNITY · V2 PREMIUM<br>Prototype visuel · données fictives</footer></main>${cockpit?'':BottomNavigation(route)}</div>`; }
// Pictogrammes réservés aux quatre accès Home : même trait, dessins distincts.
function FeaturePictogram(name) {
 const drawings = {
  plus: '<circle cx="13" cy="35" r="3"/><path d="M13 32v-8c0-5 5-7 10-7h3"/><path class="pictogram-cyan" d="M13 38h21" stroke-opacity=".55"/><circle cx="33" cy="16" r="8" fill="#102434"/><path d="M33 12v8m-4-4h8"/>',
  route: '<path d="m7 12 11-4 12 4 11-4v27l-11 4-12-4-11 4Z" stroke-opacity=".65"/><path d="M18 8v27m12-23v27" stroke-opacity=".3"/><path class="pictogram-cyan" d="M12 30c5-11 12 7 22-6"/><circle cx="12" cy="30" r="2" fill="currentColor" stroke="none"/><path d="M34 11a5 5 0 0 1 5 5c0 4-5 8-5 8s-5-4-5-8a5 5 0 0 1 5-5Z" fill="#102434"/><circle cx="34" cy="16" r="1.3" fill="currentColor" stroke="none"/>',
  users: '<path class="pictogram-cyan" d="M14 29 24 14l10 15M14 29h20" stroke-opacity=".65"/><circle cx="24" cy="12" r="4" fill="#102434"/><circle cx="12" cy="31" r="4" fill="#102434"/><circle cx="36" cy="31" r="4" fill="#102434"/><path d="M18 22a7 7 0 0 1 12 0M6 41a7 7 0 0 1 12 0m12 0a7 7 0 0 1 12 0"/>',
  chart: '<path d="M8 10v29h32" stroke-opacity=".5"/><path d="M15 33v-7m9 7V22m9 11V17" stroke-width="3"/><path class="pictogram-cyan" d="m12 20 10-7 9 2 9-8m-6 0h6v6"/>'
 };
 return `<svg class="icon feature-pictogram" viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${drawings[name] || drawings.route}</svg>`;
}
export function FeatureTile({title,description,icon,href,tone='gold'}) { return `<a class="feature-tile card ${e(tone)}" href="${e(href)}"><span class="tile-top"><span class="tile-icon">${FeaturePictogram(icon)}</span>${Icon('arrow','tile-arrow')}</span><h3>${e(title)}</h3><p>${e(description)}</p></a>`; }
export function MetricTile({value,label,unit=''}) { return `<div class="metric"><div>${e(value)}<small>${e(unit)}</small></div><span>${e(label)}</span></div>`; }
export function ScientificMetricTile(metric) { return PremiumCard(MetricTile(metric),'scientific-metric cyan'); }
export function SessionCard(session) { return `<a href="/sessions" class="card session-card"><span class="session-symbol">${Icon('route')}</span><div>${StatusBadge(session.status || 'Terminée')}<h3>${e(session.title)}</h3><p>${e(session.distance)} · ${e(session.duration)} · ${e(session.date)}</p></div>${Icon('arrow')}</a>`; }
export function RoleCard({title,description,selected=false}) { return `<button class="card role-card" aria-pressed="${selected}" data-role-choice>${Icon('user')}<strong>${e(title)}</strong><span>${e(description)}</span></button>`; }
export function SegmentedControl(items, selected) { return `<div class="segmented" role="group" aria-label="Filtrer les sessions">${items.map(item=>`<button aria-pressed="${item===selected}" data-segment="${e(item)}">${e(item)}</button>`).join('')}</div>`; }
function button(label, href, style, icon) { return href?`<a class="button ${style}" href="${e(href)}">${icon?Icon(icon):''}${e(label)}</a>`:`<button class="button ${style}" data-action="preview">${icon?Icon(icon):''}${e(label)}</button>`; }
export const PrimaryGoldButton = (label,href) => button(label,href,'button-gold','plus');
export const SecondaryDarkButton = (label,href) => button(label,href,'button-dark');
export const TerrainActionButton = (label,href) => button(label,href,'button-terrain','compass');
export const MapControlButton = (label,icon='plus') => `<button class="icon-button map-control" aria-label="${e(label)}" data-action="preview">${Icon(icon)}</button>`;
export const SearchBar = (label='Rechercher une session') => `<label class="search-bar">${Icon('search')}<input type="search" placeholder="${e(label)}" aria-label="${e(label)}"></label>`;
export const ListItem = ({title,description,href,icon='arrow'}) => `<a class="list-item" href="${e(href)}">${Icon(icon)}<span><strong>${e(title)}</strong><small>${e(description)}</small></span>${Icon('arrow')}</a>`;
export const EmptyState = (title,description,icon='compass') => `<div class="empty-state">${Icon(icon)}<h2>${e(title)}</h2><p>${e(description)}</p></div>`;
export function Toast(message) { const node=document.querySelector('#feedback'); node.textContent=message; node.classList.add('visible'); clearTimeout(Toast.timer); Toast.timer=setTimeout(()=>node.classList.remove('visible'),5000); }
export function ConfirmationDialog({title,description,onConfirm}) { const dialog=document.createElement('dialog'); dialog.innerHTML=`<h2>${e(title)}</h2><p>${e(description)}</p><div class="dialog-actions"><button class="button button-dark" data-cancel>Annuler</button><button class="button button-gold" data-confirm>Confirmer</button></div>`; document.body.append(dialog); dialog.querySelector('[data-cancel]').onclick=()=>dialog.close(); dialog.querySelector('[data-confirm]').onclick=()=>{dialog.close();onConfirm?.();}; dialog.addEventListener('close',()=>dialog.remove()); dialog.showModal(); }
export function HeroPanel() { return `<section class="discovery-hero hero card" aria-label="Découvrir PISTE"><div class="hero-terrain" aria-hidden="true"><img src="/src/assets/hero-terrain-sunset.png" alt="" width="1536" height="1024"></div><div class="hero-copy"><span class="eyebrow">EXPLORER · COMPRENDRE · PROGRESSER</span><h2>Chaque sortie<br><em>révèle un peu plus.</em></h2><a class="button button-gold discovery-cta" href="/operational">Piste opérationnelle ${Icon('arrow')}</a></div></section>`; }
export function ActiveSessions(sessions=[]) {
 if(!sessions.length)return '';
 return `<section class="active-sessions" aria-labelledby="active-sessions-title"><div class="section-title"><h2 id="active-sessions-title">Sessions en cours</h2><a class="see-all" href="/sessions">Voir tout ${Icon('arrow')}</a></div><div class="active-session-list">${sessions.map(session=>`<a class="active-session-card card" href="${e(session.href||'/sessions')}"><span class="session-map trace-${session.trace==='blue'?'blue':'red'}" aria-hidden="true"><img src="/src/assets/session-satellite-${session.terrain==='Montagne'?'ridge':'forest'}.png" alt="" width="1024" height="1024" loading="lazy"><svg viewBox="0 0 160 72" fill="none"><path class="map-trace-shadow" d="M16 57 32 41 45 47 57 33 79 39 96 20 112 26 143 12"/><path class="map-trace" d="M16 57 32 41 45 47 57 33 79 39 96 20 112 26 143 12"/><circle cx="16" cy="57" r="3"/><circle cx="143" cy="12" r="3"/></svg></span><span class="active-session-copy"><span class="session-status-row">${StatusBadge(session.status,session.status==='EN COURS'?'cyan':'gold')}${Icon('arrow','session-chevron')}</span><strong>${e(session.title)}</strong><span class="session-meta">${e(session.distance)} · ${e(session.duration)}</span><span class="session-date">${e(session.date)}</span></span></a>`).join('')}</div></section>`;
}
