import {escapeHTML as e,EmptyState,StatusBadge} from './components.mjs';

const hrefFor=session=>`/live/${session.sessionType==='ops'?'ops':'coaching'}/${encodeURIComponent(session.sessionId)}`;
const typeLabel=session=>session.sessionType==='ops'?'OPS · Observateur de trace':'Coaching · Observateur';
function sessionCard(session){return `<article class="card live-session-card" data-live-session-type="${e(session.sessionType)}"><div>${StatusBadge(session.sessionType==='ops'?'OPS LIVE':'COACHING LIVE',session.sessionType==='ops'?'terrain':'cyan')}<span class="live-role-label">${e(typeLabel(session))}</span></div><h3>${e(session.title||session.dogName||'Session en cours')}</h3><p>${e(session.ownerDisplayName||'Vous')}${session.state?` · ${e(session.state)}`:''}${session.startedAt?` · ${e(session.startedAt)}`:''}</p><a class="button button-gold" href="${e(hrefFor(session))}">Voir le Live</a></article>`;}
function group(title,items,empty){return `<section class="live-list-group"><h2>${title}</h2>${items.length?`<div class="live-session-list">${items.map(sessionCard).join('')}</div>`:`<p class="live-empty">${empty} · Les sessions autorisées apparaîtront ici.</p>`}</section>`;}
export function LiveScreen({ownSessions=[],contactSessions=[],invitations=[]}={}){
 return `<section class="live-page" data-live-screen><header class="live-heading"><span class="eyebrow">PISTE · SUIVI EN DIRECT</span><h1>Live</h1><p>Des vues en lecture seule, accessibles uniquement si le contact et la session sont autorisés.</p></header>${group('Mes sessions en cours',ownSessions,'Aucune session en cours')}${group('Sessions de mes contacts autorisées',contactSessions,'Aucune session partagée avec vous')}${group('Invitations Live',invitations,'Aucune invitation Live')}</section>`;
}

export function LiveDetailScreen(projection){
 if(!projection)return `<section class="live-page">${EmptyState('Live indisponible','Cette session n’est pas partagée avec vous ou votre accès a été révoqué.','shield')}<a class="button button-dark" href="/live">Retour au Live</a></section>`;
 if(projection.sessionType==='ops'){
  const points=projection.trace||[],path=points.map((point,index)=>`${index?'L':'M'} ${point.x} ${point.y}`).join(' ');
  return `<section class="live-page live-detail" data-live-role="ops_trace_observer"><a class="back-link" href="/live">← Live</a><header class="live-heading"><span class="eyebrow">OPS LIVE</span><h1>${e(projection.roleLabel)}</h1><p>Lecture seule · projection de trace autorisée</p></header><section class="card live-map-card"><div class="live-map-heading"><h2>Progression de la trace</h2><span>Trace mock</span></div><svg viewBox="0 0 360 220" role="img" aria-label="Trace de progression mock"><rect width="360" height="220" rx="14"/>${path?`<path d="${e(path)}"/>`:''}</svg>${path?'':`<p class="live-map-unavailable">Aucune trace de progression disponible.</p>`}${projection.corridor?`<p class="live-estimated-corridor">${e(projection.corridor.label)} · couche estimée, distincte de la trace</p>`:''}</section><section class="card live-metrics"><h2>Suivi</h2><dl><div><dt>État</dt><dd>${e(projection.state||'Indisponible')}</dd></div><div><dt>Distance</dt><dd>${projection.distance==null?'Indisponible':`${e(projection.distance)} m`}</dd></div><div><dt>Temps de pistage</dt><dd>${projection.trackingSeconds==null?'Indisponible':`${e(projection.trackingSeconds)} s`}</dd></div><div><dt>Âge / délai de piste</dt><dd>${e(projection.trackAge||'Non renseigné')}</dd></div>${projection.dogName?`<div><dt>Chien</dt><dd>${e(projection.dogName)}</dd></div>`:''}${projection.handlerName?`<div><dt>Conducteur</dt><dd>${e(projection.handlerName)}</dd></div>`:''}</dl></section>${projection.events?.length?`<section class="card live-events"><h2>Événements partageables</h2><ul>${projection.events.map(event=>`<li>${e(event.type)}</li>`).join('')}</ul></section>`:''}<p class="live-readonly-note">Observateur de trace OPS · aucune commande de mission disponible.</p></section>`;
 }
 const map=projection.map||{};
 return `<section class="live-page live-detail" data-live-role="observer"><a class="back-link" href="/live">← Live</a><header class="live-heading"><span class="eyebrow">COACHING LIVE</span><h1>Observateur</h1><p>Lecture seule · visibilité ${e(projection.modeLabel||'')}</p></header><section class="card live-coaching-state"><h2>${e(projection.phase||'Session')}</h2><p>${e(projection.dog?.name||projection.dog||'Chien indisponible')}</p><p>${e(projection.readOnly?'Aucune commande disponible.':'')}</p>${map.showStart&&map.start?`<p>Départ · ${e(map.start.label||'visible')}</p>`:''}${map.paths?.length?`<p>Tracé visible · ${map.paths.length} segment(s)</p>`:''}</section><p class="live-readonly-note">Observateur · aucune commande Coaching disponible.</p></section>`;
}
