import {escapeHTML as e,StatusBadge} from './components.mjs';
import {Icon} from './icons.mjs';
import {buildProfileSummary} from './profile-model.mjs';

const links=[
 ['account','Mon compte','Nom visible et informations personnelles','user'],['dogs','Mes chiens','Profils et chien principal','dog'],
 ['premium','Premium & JUMOLF','Votre formule et votre activation','twin'],['access','Mes accès','Accès aux espaces de PISTE Community','shield'],
 ['research','Confidentialité & recherche','Vos choix et données de contribution','science'],['notifications','Notifications','Canaux et préférences personnelles','bell'],
 ['preferences','Préférences','Unités et affichage','settings'],['about','Aide & À propos','Version, aide et informations','info']
];
const href=type=>type==='research'?'/profile/research':`/profile/${type}`;
const header=(eyebrow,title,lead='')=>`<header class="profile-heading"><span class="eyebrow">${e(eyebrow)}</span><h1>${e(title)}</h1>${lead?`<p>${e(lead)}</p>`:''}</header>`;
const row=(label,value)=>`<div class="profile-data-row"><dt>${e(label)}</dt><dd>${e(value??'Non renseigné')}</dd></div>`;
const tile=(title,detail,path,icon='arrow',badge='')=>`<a class="profile-hub-card" href="${e(path)}"><span class="profile-hub-icon">${Icon(icon)}</span><span><strong>${e(title)}</strong><small>${e(detail)}</small></span>${badge}<span class="profile-chevron" aria-hidden="true">${Icon('arrow')}</span></a>`;
const badge=(text,tone='steel')=>StatusBadge(text,tone);
const date=value=>value?new Date(value).toLocaleDateString('fr-FR'):'Aucune expiration';
const categoryLabels={training_session:'Sessions d’entraînement',gps_trace:'Traces GPS',weather:'Météo',dog_metrics:'Métriques du chien',field_events:'Événements terrain',longitudinal_history:'Historique longitudinal',reference_trace:'Trace de référence',jumolf_feedback:'Feedback JUMOLF',driver_annotations:'Annotations conducteur'};
const preference=(key,label,value,options)=>`<label class="profile-setting"><span><strong>${e(label)}</strong></span><select data-profile-preference="${e(key)}" aria-label="${e(label)}">${options.map(([option,text])=>`<option value="${e(option)}" ${value===option?'selected':''}>${e(text)}</option>`).join('')}</select></label>`;
function mainView(model,consent){
 const cards=links.map(([type,title,description,icon])=>tile(title,description,href(type),icon,type==='premium'&&model.premium.active?badge('PREMIUM','gold'):type==='research'?badge(model.research.status,model.research.enabled?'cyan':'steel'):'' )).join('');
 const selected=Object.entries(consent?.categories||{}).filter(([,on])=>on).map(([key])=>categoryLabels[key]||key);
 return `<section class="profile-page profile-home">${header('CENTRE DE CONTRÔLE PERSONNEL','Profil','Vos informations, accès et préférences au même endroit.')}<section class="profile-identity card"><span class="profile-avatar" data-avatar="${e(model.avatar)}" aria-hidden="true">${e(model.initials)}</span><div><h2>${e(model.displayName)}</h2><p>${e(model.role)} · Profil de démonstration</p><div class="profile-badges">${model.premium.active?badge('PREMIUM','gold'):badge('FREE','steel')}${model.jumolf.enabled?badge('JUMOLF','cyan'):''}${model.scientific.allowed?badge('RESEARCH','cyan'):''}${model.admin.allowed?badge('ADMIN','steel'):''}</div></div><a class="button button-subtle" href="/profile/account">Modifier</a></section><div class="profile-summary-grid"><article class="profile-summary-card"><span>MES CHIENS</span><strong>${model.dogCount}</strong><small>${e(model.primaryDog?.name||'Aucun chien principal défini')}</small><a href="/profile/dogs">Gérer mes chiens →</a>${model.jumolf.enabled&&model.primaryDog?`<a href="/jumolf/dog/${encodeURIComponent(model.primaryDog.id)}">Profil JUMOLF de ${e(model.primaryDog.name)} →</a>`:''}</article><article class="profile-summary-card profile-summary-jumolf"><span>JUMOLF</span><strong>${model.jumolf.enabled?'Activé':model.jumolf.valid?'À activer':'Aucun accès'}</strong><small>${e(model.jumolf.source)}</small><a href="/profile/premium">Gérer Premium & JUMOLF →</a></article><article class="profile-summary-card"><span>RECHERCHE</span><strong>${e(model.research.status)}</strong><small>${model.research.enabledCategories} catégorie(s) autorisée(s) · OPS ${model.research.opsShared?'partagé':'non partagé'}</small><a href="/profile/research">Gérer mes autorisations →</a></article></div><nav class="profile-hub-grid" aria-label="Réglages du profil">${cards}</nav>${model.admin.allowed?`<section class="profile-admin-entry">${tile('Administration','Console de démonstration','/admin','shield',badge('ADMIN','steel'))}</section>`:''}${model.scientific.allowed?`<section class="profile-scientific-entry">${tile('Espace scientifique','Laboratoire de données privé','/scientific','science',badge('ACCÈS AUTORISÉ','cyan'))}</section>`:''}<p class="profile-local-note">Réglages de démonstration · données locales à cette visite.</p></section>`;
}
function accountView(model){return `<section class="profile-page">${header('VOTRE ESPACE','Mon compte','Le nom visible est partagé avec votre profil Communauté.')}<a class="profile-back" href="/profile">← Profil</a><article class="profile-panel"><div class="profile-account-hero"><span class="profile-avatar large" data-avatar="${e(model.avatar)}">${e(model.initials)}</span><div><h2>${e(model.displayName)}</h2><p>Profil de démonstration · ${e(model.role)}</p></div></div><form data-profile-form="account" class="profile-form"><label>Nom visible Communauté<input name="displayName" maxlength="80" required value="${e(model.displayName)}" aria-describedby="profile-name-help"></label><small id="profile-name-help">Ce nom apparaît aussi dans Communauté.</small><label>Avatar de démonstration<select name="avatar"><option value="initials" ${model.avatar==='initials'?'selected':''}>Initiales</option><option value="terrain" ${model.avatar==='terrain'?'selected':''}>Terrain · illustration locale</option><option value="silhouette" ${model.avatar==='silhouette'?'selected':''}>Silhouette</option></select></label><label>Email de démonstration<input readonly value="${e(model.email)}"></label><label>ID compte<input readonly value="${e(model.userId||'mock-account')}" class="profile-id-field"></label><label>Date d’inscription<input readonly value="Donnée non disponible"></label><p role="status" aria-live="polite"></p><button class="button button-gold" type="submit">Enregistrer les modifications</button></form><p class="profile-local-note">Modification mock en mémoire de visite. Aucune Auth réelle.</p></article></section>`;}
function dogsView(model,profileStore){const selected=profileStore.snapshot().primary_dog_id;const options=[['','Aucun chien principal'],...model.dogs.map(dog=>[dog.id,dog.name])];return `<section class="profile-page">${header('VOTRE ÉQUIPE','Mes chiens','Les profils et les données viennent du module Chiens existant.')}<a class="profile-back" href="/profile">← Profil</a><article class="profile-panel"><label class="profile-setting"><span><strong>Chien principal</strong><small>Utilisé pour les raccourcis et futures analyses par défaut.</small></span><select data-profile-primary-dog aria-label="Définir le chien principal">${options.map(([id,name])=>`<option value="${e(id)}" ${selected===id?'selected':''}>${e(name)}</option>`).join('')}</select></label><a class="button button-subtle" href="/dogs">Gérer mes chiens</a></article><div class="profile-dog-list">${model.dogs.map(dog=>`<article class="profile-dog-card"><span class="profile-dog-mark" aria-hidden="true">${Icon('dog')}</span><div><h2>${e(dog.name)}</h2><p>${e(dog.breed||dog.specialty||'Race non renseignée')} · ${e(dog.status||'Statut non renseigné')}</p><small>${Array.isArray(dog.sessions)?dog.sessions.length:0} session(s) liée(s) · JUMOLF selon l’accès du compte</small></div><a class="button button-subtle" href="/dogs/${encodeURIComponent(dog.id)}">Voir le profil</a></article>`).join('')||'<div class="profile-panel">Aucun chien enregistré.</div>'}</div></section>`;}
function premiumView(model){return `<section class="profile-page">${header('VOS FONCTIONNALITÉS','Premium & JUMOLF','L’accès, son origine et son activation restent distincts.')}<a class="profile-back" href="/profile">← Profil</a><article class="profile-panel profile-premium-panel"><div class="profile-panel-heading"><span>PREMIUM</span>${badge(model.premium.active?'ACTIF':'NON ACTIF',model.premium.active?'gold':'steel')}</div><dl>${row('État',model.premium.active?'Actif':'Non actif')}${row('Origine',model.premium.source||'Aucune')}${row('Expiration',date(model.premium.expiresAt))}</dl><a class="button button-subtle" href="/jumolf/premium">Découvrir Premium</a></article><article class="profile-panel profile-jumolf-panel"><div class="profile-panel-heading"><span>JUMOLF</span>${badge(model.jumolf.enabled?'ACTIVÉ':model.jumolf.valid?'À ACTIVER':'VERROUILLÉ',model.jumolf.enabled?'cyan':'steel')}</div><dl>${row('Entitlement',model.jumolf.entitlement)}${row('Origine',model.jumolf.source)}${row('Expiration',date(model.jumolf.expiresAt))}${row('Activation',model.jumolf.enabled?'Activé par le membre':'Non activé')}${row('Onboarding',model.jumolf.onboardingComplete?'Terminé':'À terminer')}</dl>${model.jumolf.valid?`<a class="button button-gold" href="/jumolf">${model.jumolf.enabled?'Gérer JUMOLF':'Activer JUMOLF'}</a>`:`<a class="button button-gold" href="/jumolf/access-code">Utiliser un code d’accès</a>`}<a class="profile-text-link" href="/jumolf/access-code">Utiliser un code d’accès</a><p>Les consentements JUMOLF sont gérés dans JUMOLF. La contribution scientifique reste séparée.</p></article></section>`;}
function accessView(model){return `<section class="profile-page">${header('VOS AUTORISATIONS','Mes accès','Cette page résume les accès issus des systèmes existants.')}<a class="profile-back" href="/profile">← Profil</a><div class="profile-access-list"><article>${badge(model.premium.active?'ACTIF':'INACTIF',model.premium.active?'gold':'steel')}<h2>Premium</h2><p>${e(model.premium.source||'Aucun accès Premium')}</p></article><article>${badge(model.jumolf.enabled?'ACTIVÉ':model.jumolf.valid?'ÉLIGIBLE':'VERROUILLÉ',model.jumolf.enabled?'cyan':'steel')}<h2>JUMOLF</h2><p>${e(model.jumolf.source)} · ${model.jumolf.enabled?'Activé':'Non activé'}</p><a href="/jumolf">Ouvrir JUMOLF</a></article><article>${badge(model.scientific.allowed?'AUTORISÉ':'NON AUTORISÉ',model.scientific.allowed?'cyan':'steel')}<h2>Espace scientifique</h2><p>${e(model.scientific.role||'Aucun accès scientifique pour ce profil')}</p>${model.scientific.allowed?'<a href="/scientific">Ouvrir l’Espace scientifique</a>':''}</article><article>${badge(model.research.status.toUpperCase(),model.research.enabled?'cyan':'steel')}<h2>Contribution recherche</h2><p>${model.research.enabledCategories} catégorie(s) active(s) · OPS ${model.research.opsShared?'partagé':'non partagé'}</p><a href="/profile/research">Gérer mes choix</a></article>${model.admin.allowed?`<article>${badge('ADMIN','steel')}<h2>Administration</h2><p>Accès selon le gate Admin mock.</p><a href="/admin">Ouvrir la Console Admin</a></article>`:''}</div></section>`;}
function researchView(model,consent){const categories=Object.entries(consent?.categories||{}).filter(([,on])=>on).map(([key])=>categoryLabels[key]||key);return `<section class="profile-page">${header('VOS CHOIX','Confidentialité & recherche','La gestion des consentements reste dans le module dédié.')}<a class="profile-back" href="/profile">← Profil</a><article class="profile-panel"><div class="profile-panel-heading"><h2>Contribution scientifique</h2>${badge(model.research.status.toUpperCase(),model.research.enabled?'cyan':'steel')}</div><dl>${row('Catégories autorisées',categories.length?categories.join(' · '):'Aucune')}${row('OPS',model.research.opsShared?'Partagé partiellement':'Non partagé')}${row('Sessions éligibles',model.research.eligibleSessions??'Voir le détail')}${row('Sessions exclues',model.research.excludedSessions??'Voir le détail')}${row('Version consentement',model.research.consentVersion||'Disponible dans le détail')}</dl><a class="button button-subtle" href="/profile/research">Gérer mes autorisations</a><a href="/profile/research/data">Mes données de recherche</a><a href="/profile/research/transparency">Comment mes données sont utilisées</a></article></section>`;}
function notificationsView(notificationPreferences){const toggles=[['notify_live_in_app','Dans l’application','Cloche et centre de notifications'],['notify_live_email','Email','Préférence mock · aucun email envoyé'],['notify_live_push','Web Push','Préférence mock · aucun Push envoyé']];return `<section class="profile-page">${header('VOS ALERTES','Notifications','Choisissez les canaux pour les événements pris en charge.')}<a class="profile-back" href="/profile">← Profil</a><article class="profile-panel profile-notification-options">${toggles.map(([key,label,description])=>`<label class="profile-toggle"><span><strong>${e(label)}</strong><small>${e(description)}</small></span><input type="checkbox" data-profile-notification="${e(key)}" ${notificationPreferences?.[key]?'checked':''} aria-label="${e(label)}"></label>`).join('')}</article><article class="profile-panel"><h2>Autres notifications</h2><p>Invitations, Communauté, JUMOLF et alertes liées aux séances.</p><span class="profile-coming-soon">Disponible prochainement</span><a class="profile-text-link" href="/notifications">Ouvrir le centre de notifications</a></article><p class="profile-local-note">Les préférences Email et Push ne déclenchent aucun envoi réel.</p></section>`;}
function preferencesView(profileStore){const prefs=profileStore.snapshot().preferences;return `<section class="profile-page">${header('VOTRE CONFORT','Préférences','Quelques réglages personnels conservés en mémoire locale.')}<a class="profile-back" href="/profile">← Profil</a><article class="profile-panel profile-settings-list">${preference('theme','Apparence',prefs.theme,[['system','Système'],['dark','Sombre'],['light','Clair']])}${preference('distance_unit','Unité de distance',prefs.distance_unit,[['km','Kilomètres'],['m','Mètres']])}${preference('speed_unit','Vitesse',prefs.speed_unit,[['km/h','km/h']])}${preference('time_format','Format horaire',prefs.time_format,[['24h','24 heures'],['12h','12 heures']])}${preference('map_default','Carte par défaut',prefs.map_default,[['standard','Standard'],['topographic','Topographique'],['satellite','Satellite']])}${preference('density','Densité interface',prefs.density,[['comfortable','Confortable'],['compact','Compact']])}${preference('language','Langue',prefs.language,[['fr','Français'],['en','English']])}</article><article class="profile-panel"><h2>Réglages terrain</h2><p>Vibration, orientation carte et recentrage automatique</p><span class="profile-coming-soon">À venir</span></article></section>`;}
function aboutView(appVersion){return `<section class="profile-page">${header('PISTE COMMUNITY','Aide & À propos','Informations sur cette version de démonstration.')}<a class="profile-back" href="/profile">← Profil</a><article class="profile-panel"><h2>PISTE Community</h2><dl>${row('Version',appVersion?.app_version||'Non disponible')}${row('Build',appVersion?.build||'Non disponible')}${row('Environnement',appVersion?.environment||'Prototype local')}</dl><span class="profile-coming-soon">Simulation locale</span></article><article class="profile-panel"><h2>Besoin d’aide ?</h2><div class="profile-help-links"><a href="/jumolf">Comprendre JUMOLF</a><a href="/profile/research/transparency">Confidentialité et recherche</a><a href="/notifications">Centre de notifications</a><span>FAQ · À venir</span><span>Signaler un problème · À venir</span></div></article><p class="profile-local-note">Prototype Premium · aucune condition juridique finale ni support externe n’est configuré.</p></section>`;}

export function ProfileScreen({route,user,profileStore,dogs=[],communityProfile,jumolfAccess={},jumolfState={},consent={},scientificAccess={},adminAccess={},notificationPreferences={},appVersion={}}={}){
 const profileState=profileStore?.snapshot()||{};const model=buildProfileSummary({user,dogs,primaryDogId:profileState.primary_dog_id,jumolfAccess,jumolfState,consent,scientificAccess,adminAccess,communityProfile});model.avatar=profileState.avatar||'initials';
 switch(route?.type){case'home':return mainView(model,consent);case'account':return accountView(model);case'dogs':return dogsView(model,profileStore);case'premium':return premiumView(model);case'access':return accessView(model);case'research':return researchView(model,consent);case'notifications':return notificationsView(notificationPreferences);case'preferences':return preferencesView(profileStore);case'about':return aboutView(appVersion);default:return '<section class="profile-page"><h1>Section Profil indisponible</h1></section>';}
}
