import { TrackBuilderScreen, trackBuilderEntry } from './track-builder-screen.mjs';
import { createTrackLibrary } from './track-library.mjs';
import { CoachingScreen } from './coaching-screen.mjs';
import { createDraft } from './coaching.mjs';
import * as C from './components.mjs';
import { Icon } from './icons.mjs';
import { mock } from './data.mjs';
export const routes = Object.freeze({
 '/auth':['Bienvenue','premiumBrandDog'], '/auth/login':['Se connecter','user'], '/auth/signup':['Créer un compte','user'], '/auth/forgot':['Mot de passe oublié','user'],
 '/jumolf':['JUMOLF · Jumeau olfactif','twin'], '/scientific':['Espace scientifique privé','science'],
 '/coaching/session':['Préparation coaching','route'], '/qa/coaching':['QA Coaching · DEV','science'], '/track-builder':['Créateur de tracé','route'], '/operational':['Pistage opérationnel','navLive'], '/': ['Accueil','home'], '/live':['Live','navLive'], '/notifications':['Notifications','bell'], '/notifications/preferences':['Préférences notifications','bell'], '/dogs':['Mes chiens','dog'], '/sessions':['Sessions','navSessions'], '/tracks':['Mes pistes','route'], '/community':['Communauté','users'], '/profile':['Profil','user'], '/profile/account':['Mon compte','user'], '/profile/dogs':['Mes chiens','dog'], '/profile/premium':['Premium & JUMOLF','twin'], '/profile/access':['Mes accès','shield'], '/profile/notifications':['Notifications','bell'], '/profile/preferences':['Préférences','settings'], '/profile/about':['Aide & À propos','info'], '/profile/research':['Contribution scientifique','science'], '/profile/research/data':['Mes données de recherche','science'], '/profile/research/transparency':['Transparence recherche','science'], '/new-session':['Nouvelle session','plus'], '/olfactory-twin':['Jumeau olfactif','twin'], '/admin':['Admin / Operations','shield'], '/statistics':['Statistiques','chart']
});
export function HomeScreen(user = mock.user, activeSessions = mock.activeSessions, jumolfAccess = {entitlement_valid:false,jumolf_enabled:false,locked_reason:'none'}, adminAccess = false) {
 return `<section class="home-intro" aria-label="Bienvenue sur le terrain"><div class="header-terrain" aria-hidden="true"></div><div class="greeting"><div><p>Bonjour ${C.escapeHTML(user.name)},</p><h1>Prêts pour le terrain ?</h1></div></div><p class="eyebrow">LE TERRAIN NOUS RELIE</p><p class="home-tagline">Une équipe. Une piste.<br><strong>La même passion.</strong></p></section>${C.HeroPanel()}
 <section aria-label="Vos accès principaux" class="feature-grid">${[
 {title:'Nouvelle session',description:'Créer un exercice avec coaching',icon:'plus',href:'/new-session'},
 {title:'Mes pistes',description:'Historique et replay',icon:'route',href:'/tracks'},
 {title:'Communauté',description:'Partager et découvrir',icon:'users',href:'/community'},
 {title:'Statistiques',description:'Suivi et progression',icon:'chart',href:'/statistics'}
 ].map(C.FeatureTile).join('')}</section>
 ${trackBuilderEntry()}
 ${C.ActiveSessions(activeSessions)}
 ${(()=>{const title=!jumolfAccess.entitlement_valid?'JUMOLF Premium':jumolfAccess.jumolf_enabled?'Jumeau olfactif · JUMOLF':'Activer JUMOLF',cta=!jumolfAccess.entitlement_valid?'Découvrir JUMOLF Premium':jumolfAccess.jumolf_enabled?'Explorer JUMOLF':'Activer JUMOLF';return `<a class="card twin-card" href="/jumolf" data-jumolf-home-access="${jumolfAccess.entitlement_valid?jumolfAccess.jumolf_enabled?'active':'eligible':'locked'}"><div class="twin-heading"><span class="eyebrow cyan">INTELLIGENCE OLFACTIVE</span>${Icon('arrow')}</div><div class="twin-content"><div><h2>${C.escapeHTML(title)}</h2><p>Comprendre la piste.<br>Révéler l’intelligence olfactive.</p></div><span class="twin-science" aria-hidden="true"><img src="/src/assets/olfactory-dog-science.png" alt="" width="1536" height="1024" loading="lazy"></span></div><span class="text-link">${C.escapeHTML(cta)} ${Icon('arrow')}</span></a>`;})()}
 ${(user.permissions?.research || adminAccess) ? `<section class="explore-section">${C.SectionTitle('Votre espace expert')}${user.permissions?.research ? C.ListItem({title:'Recherche scientifique',description:'La science au service du terrain',href:'/scientific',icon:'science'}) : ''}${adminAccess ? C.ListItem({title:'Admin / Operations',description:'Console de démonstration',href:'/admin',icon:'shield'}) : ''}</section>` : ''}`;
}
export function PlaceholderScreen(route, user = mock.user, jumolfAccess = null) {
 if(route.startsWith('/auth')) return AuthScreen(route);
 if(route==='/track-builder')return TrackBuilderScreen({view:'list'},createTrackLibrary().list());
 if(route==='/new-session')return CoachingScreen(createDraft(user,[{id:'nox',...mock.dog}]));
 const [title,icon] = routes[route] || ['Page introuvable','compass'];
 let body='';
 if (route==='/admin' && !user.permissions?.admin) body=C.EmptyState('Espace réservé','Ce profil de démonstration ne dispose pas de cet accès.','shield');
 else if(route==='/live') body=C.EmptyState('Le terrain en direct','Les sessions disponibles apparaîtront dans l’espace Live.','navLive');
 else if(route==='/sessions') body=`${C.SearchBar()}${C.SegmentedControl(['Toutes','À reprendre','Terminées'],'Toutes')}<div id="session-results">${C.SessionCard(mock.session)}${C.SessionCard(mock.recent)}</div>`;
 else if(route==='/statistics') body=`<div class="metrics-grid">${mock.stats.map(C.MetricTile).join('')}</div>${C.EmptyState('Chaque session compte','Les courbes de progression prendront place ici. Les chiffres présentés sont fictifs.','chart')}`;
 else if(route==='/profile') {const premiumActive=jumolfAccess?.entitlement==='premium';body=C.PremiumCard(`<span class="avatar large">${C.escapeHTML(user.initials || user.name.slice(0,1))}</span><h2>${C.escapeHTML(user.name)}</h2><p>${mock.user.role} · Profil de démonstration</p>`,'profile-card') + `<section class="profile-premium-summary"><span class="eyebrow">ACCÈS DU COMPTE · MOCK</span><h2>Premium &amp; JUMOLF</h2><dl><div><dt>Premium</dt><dd>${premiumActive?'Actif':'Non actif'}</dd></div><div><dt>Accès JUMOLF</dt><dd>${C.escapeHTML(jumolfAccess?.origin_label||'Aucun accès')}</dd></div><div><dt>Expiration</dt><dd>${jumolfAccess?.expires_at?C.escapeHTML(new Date(jumolfAccess.expires_at).toLocaleDateString('fr-FR')):'Aucune expiration renseignée'}</dd></div><div><dt>JUMOLF</dt><dd>${jumolfAccess?.jumolf_enabled?'Activé':'Non activé'}</dd></div></dl><a class="button button-subtle" href="/jumolf">Gérer l’accès JUMOLF</a></section><a class="list-item" href="/profile/research"><span>${Icon('science')}</span><span><strong>Contribuer à la recherche scientifique</strong><small>Choisir les catégories partagées et consulter mes données</small></span>${Icon('arrow')}</a><button class="button button-dark" data-action="logout">Se déconnecter</button>`;}

 else if(route==='/olfactory-twin') body=`${C.PremiumCard(`<span class="twin-orbit">${Icon('twin')}</span><h2>Explorer l’invisible</h2><p>Vent, terrain, trace et perception : un futur espace pour mieux comprendre le travail de votre chien.</p>${C.StatusBadge('Aperçu visuel','cyan')}`,'twin-detail')}${C.EmptyState('Le terrain a encore tant à raconter','La visualisation olfactive sera développée dans un prochain bloc. Aucun calcul scientifique n’est exécuté.','twin')}`;
 else body=C.EmptyState(route==='/community'?'Le terrain se partage':route==='/admin'?'Un regard sur les opérations':'Cette piste n’existe pas',route==='/community'?'Vos échanges et rencontres prendront place ici.':route==='/admin'?'L’espace opérationnel est uniquement présenté visuellement. Aucun droit réel n’est associé à ce profil.':'Revenez à l’accueil pour continuer.',icon);
 return `<a class="back-link" href="/">← Accueil</a><section class="page-heading"><span class="eyebrow">PISTE COMMUNITY</span><h1>${title}</h1><p>Prototype Premium · aperçu de l’espace</p></section><div class="page-content">${body}</div>${C.SecondaryDarkButton('Retour à l’accueil','/')}`;
}

export function AuthScreen(route) {
 const brand = `<a class="brand" href="/auth" aria-label="PISTE Community, bienvenue">${Icon('premiumBrandDog')}<span>PISTE<small>COMMUNITY</small></span></a>`;
 if(route==='/auth') return `<div class="auth-shell auth-entry auth-welcome"><main id="main" tabindex="-1"><h1 class="auth-image-label">Bienvenue sur PISTE Community</h1><div class="auth-welcome-art"><img src="/src/assets/piste-community-accueil-original.jpg" alt="PISTE Community — Le terrain nous relie. Observer, analyser, partager, progresser. Un chien de pistage suit une piste dorée. Le pistage dans une nouvelle dimension." width="864" height="1536" fetchpriority="high"></div><nav class="auth-welcome-actions" aria-label="Accéder à PISTE Community"><a class="button auth-welcome-login" href="/auth/login">Se connecter</a><a class="auth-welcome-signup" href="/auth/signup">Créer un compte</a></nav></main></div>`;
 const signup=route==='/auth/signup', forgot=route==='/auth/forgot';
 const field=(name,label,type='text',autocomplete='')=>`<label class="auth-field" for="${name}">${label}<input id="${name}" name="${name}" aria-label="${label}" type="${type}" autocomplete="${autocomplete}" required ${type==='password'?'minlength="8"':''} aria-describedby="${name}-error"><span id="${name}-error" class="field-error"></span></label>`;
 return `<div class="auth-shell auth-form-shell ${!signup&&!forgot?'auth-login-premium':''}"><header>${brand}</header><main id="main" tabindex="-1"><a class="back-link" href="/auth">← Retour</a><section class="auth-heading"><span class="eyebrow">VOTRE PROCHAINE PISTE</span><h1>${signup?'Créer un compte':forgot?'Mot de passe oublié':'Se connecter'}</h1><p>${signup?'Rejoignez une passion commune.':forgot?'Simulez la récupération de votre accès.':'Retrouvez votre binôme et vos pistes.'}</p></section><form data-auth="${signup?'signup':forgot?'forgot':'login'}" novalidate>${signup?`<div class="auth-names">${field('firstName','Prénom','text','given-name')}${field('lastName','Nom','text','family-name')}</div>`:''}${field('email','Email','email','email')}${forgot?'':field('password','Mot de passe','password',signup?'new-password':'current-password')}${signup?field('confirmPassword','Confirmer le mot de passe','password','new-password'):''}${forgot?'':'<p class="password-hint">8 caractères minimum pour cette démonstration.</p>'}<p class="auth-result" role="status" aria-live="polite"></p><button class="button button-gold" type="submit">${signup?'Créer mon compte':forgot?'Simuler la récupération':'Se connecter'}</button></form>${!signup&&!forgot?'<a class="back-link forgot-link" href="/auth/forgot">Mot de passe oublié</a><p class="auth-switch">Première piste ? <a href="/auth/signup">Créer un compte</a></p>':''}<p class="auth-note">Prototype uniquement. Aucun compte créé.<br>Utilisez des informations fictives.</p></main></div>`;
}
