import {escapeHTML as e,StatusBadge,EmptyState} from './components.mjs';
import {Icon} from './icons.mjs';

const filters=['Toutes','En cours','Terminées','Archivées'];
const item=row=>`<a class="card session-history-card ${row.kind==='operational'?'operational-session-row':''}" href="${e(row.href)}" data-session-id="${e(row.id)}" data-session-kind="${e(row.kind)}"${row.provenance?` data-session-provenance="${e(row.provenance)}"`:''}><span class="session-history-mark" aria-hidden="true">${Icon(row.kind==='operational'?'navLive':'navSessions')}</span><span class="session-history-copy"><span class="session-history-badges">${StatusBadge(row.status,row.status==='En cours'?'cyan':row.status==='Archivée'?'neutral':'gold')}<small>${e(row.provenance||row.modeLabel)}</small></span><strong>${e(row.title)}</strong><span>${e(row.dogName)} · ${e(row.roleLabel)}</span>${row.trackingLabel?`<small class="operational-tracking-substate">${e(row.trackingLabel)}</small>`:''}<small>${e(row.date)}</small>${row.kind==='operational'?`<small>Âge de piste au départ · ${e(row.trackAge||'non renseigné')}</small>`:row.trackAgeLabel?`<small>Âge de piste au départ · ${e(row.trackAgeLabel)}</small>`:''}<small>${e(row.distance||'Aucune donnée disponible')} · ${e(row.duration||'Aucune donnée disponible')}</small></span><span class="session-history-arrow" aria-hidden="true">${Icon('arrow')}</span></a>`;

export function SessionListResults(rows){return rows.length?rows.map(item).join(''):EmptyState('Aucune session','Aucune session ne correspond à ces filtres.','route');}

export function SessionListScreen(rows,{filter='Toutes',query='',dogId='',dogName=''}={}){
 return `<section class="sessions-page" data-consultation-view="sessions"><a class="back-link" href="/">← Accueil</a><header class="sessions-heading"><span class="eyebrow">HISTORIQUE · MOCK EN MÉMOIRE</span><h1>Sessions</h1><p>Retrouvez les sessions et leurs débriefs. Les éléments terminés sont en lecture seule.</p></header>${dogId?`<p class="sessions-dog-filter" data-filter-dog="${e(dogId)}">Filtre chien · ${e(dogName||'Chien sélectionné')} <a href="/sessions">Effacer</a></p>`:''}<label class="sessions-search"><span class="sr-only">Rechercher dans les sessions</span><input type="search" data-session-query value="${e(query)}" placeholder="Rechercher une session" aria-label="Rechercher une session"></label><div class="sessions-filters" role="group" aria-label="Filtrer les sessions">${filters.map(value=>`<button type="button" data-session-filter="${value}" aria-pressed="${value===filter}">${value}</button>`).join('')}</div><div class="sessions-results" id="session-results" aria-live="polite">${SessionListResults(rows)}</div></section>`;
}

export function SessionDetailScreen(view){
 if(!view)return `<section class="sessions-not-found">${EmptyState('Session introuvable','Elle n’est pas disponible dans les données mock de cette visite.','navSessions')}<a class="button button-dark" href="/sessions">Retour aux sessions</a></section>`;
 const participants=view.participants?.length?`<ul class="session-participant-list">${view.participants.map(person=>`<li><strong>${e(person.name||'Participant indisponible')}</strong><span>${e(person.role||'Fonction indisponible')} · ${e(person.status||'Statut indisponible')}</span></li>`).join('')}</ul>`:EmptyState('Participants indisponibles','Aucun participant n’est présent dans ce résumé.','users');
 const rows=[['Chien',view.dog?.name||'Aucune donnée disponible'],['Mode',view.mode||'Aucune donnée disponible'],['Créateur',view.creatorRole||'Aucune donnée disponible'],['Date',view.date||'Aucune donnée disponible'],['Durée',view.duration||'Aucune donnée disponible'],['Distance',view.distance||'Aucune donnée disponible'],...(view.trackAgeAtSearchStart!==undefined?[['Âge de piste au départ recherche',view.trackAgeLabel||'Indisponible']]:[])];
 return `<section class="session-detail-page" data-consultation-view="session-detail" data-session-phase="${e(view.phase||'SUMMARY_ONLY')}"><a class="back-link" href="/sessions">← Sessions</a><header class="sessions-heading"><span class="eyebrow">${view.status==='Archivée'?'ARCHIVES':'CONSULTATION'} · MOCK</span><h1>${e(view.title)}</h1><p>${StatusBadge(view.status||'Statut indisponible',view.status==='En cours'?'cyan':view.status==='Archivée'?'neutral':'gold')} <span>${view.readOnly?'Lecture seule':'Résumé de démonstration'}</span></p></header>${view.canResume?`<a class="button button-gold session-return-coaching" href="/coaching/session">Reprendre dans Coaching</a>`:''}<section class="card session-detail-card"><span class="eyebrow">SYNTHÈSE</span><dl>${rows.map(([label,value])=>`<div><dt>${e(label)}</dt><dd>${e(value)}</dd></div>`).join('')}</dl><div class="session-detail-participants"><h2>Participants</h2>${participants}</div></section>${view.observations?.length?`<section class="card session-detail-card"><span class="eyebrow">OBSERVATIONS</span><ul class="session-observation-list">${view.observations.map(note=>`<li>${e(note)}</li>`).join('')}</ul></section>`:''}${view.status==='En cours'?`<aside class="sessions-readonly-note">La session active reste dans le parcours Coaching. Cette page ne présente aucun contrôle terrain.</aside>`:view.report?`<section class="session-post-actions"><a class="button button-dark" href="/sessions/${e(encodeURIComponent(view.id))}/debrief">Consulter le débrief</a><a class="button button-gold" href="/sessions/${e(encodeURIComponent(view.id))}/replay">Ouvrir le replay</a><a class="button button-gold" href="/community/new?sourceType=session&amp;sourceId=${encodeURIComponent(view.id)}">Partager dans la Communauté</a></section><p class="sessions-readonly-note">${view.poseAvailable?'Tracé de pose disponible':'Tracé de pose indisponible'} · ${view.searchAvailable?'Tracé de relève disponible':'Tracé de relève indisponible'}</p>`:''}</section>`;
}
