import {escapeHTML as e,StatusBadge,EmptyState} from './components.mjs';
import {MapShell} from './map-shell.mjs';

export function TrackListScreen(rows=[],history=[]){
 const historySection=`<section class="tracks-history" aria-labelledby="tracks-history-title"><header class="tracks-subheading"><span class="eyebrow">SESSIONS TERMINÉES · LECTURE SEULE</span><h2 id="tracks-history-title">Historique terrain</h2><p>Retrouvez vos sessions, débriefs et replays.</p></header>${history.length?`<div class="tracks-history-list">${history.map(row=>`<article class="card tracks-session-card" data-history-session="${e(row.id)}"><div><span>${StatusBadge(row.status,row.status==='Archivée'?'neutral':'gold')}</span><strong>${e(row.title)}</strong><small>${e(row.dogName)} · ${e(row.date)}</small></div><nav aria-label="Consulter ${e(row.title)}"><a href="${e(row.href)}">Détail</a>${row.replayHref?`<a href="${e(row.replayHref)}">Replay</a>`:'<span class="replay-unavailable">Replay indisponible</span>'}</nav></article>`).join('')}</div>`:EmptyState('Aucun historique disponible','Les sessions terminées et archivées apparaîtront ici, avec leurs replays et traces disponibles.','navSessions')}</section>`;
 const trackSection=`<section class="tracks-library" aria-labelledby="tracks-library-title"><header class="tracks-subheading"><span class="eyebrow">TRACÉS ET PROVENANCE</span><h2 id="tracks-library-title">Tracés consultables</h2><p>Pistes préparées, imports et traces associées aux sessions.</p></header><a class="button button-dark tracks-editor-link" href="/track-builder">Ouvrir le créateur de tracé</a><div class="tracks-results">${rows.length?rows.map(row=>`<a class="card track-record-card" href="${e(row.href)}" data-track-id="${e(row.id)}"><span class="track-record-icon" aria-hidden="true">⌁</span><span><span class="track-record-badges">${StatusBadge(row.kind==='gpx'?'GPX MOCK':row.kind==='pose'?'POSE':row.kind==='search'?'RELÈVE':row.kind==='reference'?'RÉFÉRENCE':'PRÉPARÉ',row.kind==='search'?'cyan':'gold')}</span><strong>${e(row.name)}</strong><small>${e(row.provenance)}${row.fileName?` · ${e(row.fileName)}`:''}</small>${row.geometryAvailable?'<small>Géométrie mock disponible</small>':'<small>Aucune donnée géométrique disponible</small>'}</span><span aria-hidden="true">›</span></a>`).join(''):EmptyState('Aucun tracé disponible','Les pistes préparées ou les traces associées aux sessions apparaîtront ici.','route')}</div></section>`;
 return `<section class="tracks-page" data-consultation-view="tracks"><a class="back-link" href="/">← Accueil</a><header class="sessions-heading"><span class="eyebrow">HISTORIQUE ET REPLAY · MOCK EN MÉMOIRE</span><h1>Mes pistes</h1><p>Retrouvez vos anciennes pistes, les sessions terminées, leurs débriefs et les traces disponibles.</p></header>${historySection}${trackSection}</section>`;
}

export function TrackDetailScreen(item){
 if(!item)return `<section class="tracks-not-found">${EmptyState('Piste introuvable','Elle n’est pas disponible dans cette visite mock.','route')}<a class="button button-dark" href="/tracks">Retour à Mes pistes</a></section>`;
 const pointSegments=[];
 for(const point of item.points||[]){if(!pointSegments.length||point.breakBefore)pointSegments.push([]);pointSegments.at(-1).push(point);}
 const preparedMap=item.geometryAvailable&&pointSegments.some(segment=>segment.length>1)?MapShell({paths:pointSegments.filter(segment=>segment.length>1).map((segment,index)=>({kind:'reference',label:pointSegments.length>1?`Parcours préparé · segment ${index+1} · mock`:'Parcours préparé · mock',d:segment.map((point,pointIndex)=>`${pointIndex?'L':'M'} ${point.x} ${point.y}`).join(' ')})),markers:[],start:item.points[0],arrival:item.points.at(-1),showStart:true,viewerId:null,orientation:null},{postSession:true}):null;
 const map=item.geometryAvailable?(item.map?MapShell(item.map,{postSession:true}):preparedMap):'<p class="track-geometry-unavailable">Aucune donnée géométrique disponible pour cet élément.</p>';
 const sourceReadonly=Boolean(item.sessionId);
 const actions=sourceReadonly
  ?`${item.copySource?`<button type="button" class="button button-gold" data-track-action="copy-session" data-track-source="${e(item.id)}">Créer une copie modifiable</button>`:'<p class="track-geometry-unavailable">Copie indisponible : géométrie continue non disponible dans les données mock.</p>'}`
  :item.libraryId?`${item.geometryAvailable?`<a class="button button-gold" href="/track-builder?edit=${e(encodeURIComponent(item.libraryId))}" data-track-action="edit">Modifier le tracé</a><button type="button" class="button button-dark" data-track-action="duplicate" data-library-id="${e(item.libraryId)}">Dupliquer</button>`:`<form class="track-rename-form" data-track-rename="${e(item.libraryId)}"><label>Renommer cette entrée mock<input name="name" maxlength="80" required value="${e(item.name)}"></label><button type="submit" class="button button-dark">Renommer</button></form>`}<button type="button" class="button button-dark" data-track-action="delete" data-library-id="${e(item.libraryId)}">Supprimer</button>`:'<a class="button button-gold" href="/track-builder">Ouvrir le créateur de tracé</a>';
 return `<section class="track-detail-page" data-track-detail="${e(item.id)}"><a class="back-link" href="/tracks">← Mes pistes</a><header class="sessions-heading"><span class="eyebrow">PROVENANCE DU TRACÉ</span><h1>${e(item.name)}</h1><p>${StatusBadge(item.kind==='gpx'?'GPX MOCK':item.kind==='pose'?'Tracé de pose':item.kind==='search'?'Tracé de relève':item.kind==='reference'?'Référence préparée':'Tracé préparé','gold')}</p></header><section class="card track-detail-card"><dl><div><dt>Origine</dt><dd>${e(item.provenance)}</dd></div><div><dt>Session source</dt><dd>${e(item.sessionId||'Aucune donnée disponible')}</dd></div>${item.fileName?`<div><dt>Fichier GPX mock</dt><dd>${e(item.fileName)} · aucun fichier lu</dd></div>`:''}</dl>${map}${sourceReadonly?`<a class="button button-dark" href="/sessions/${e(encodeURIComponent(item.sessionId))}">Consulter la session source</a>`:''}<a class="button button-gold" href="/community/new?sourceType=track&amp;sourceId=${encodeURIComponent(item.id)}">Partager dans la Communauté</a>${actions}</section></section>`;
}
