const fs=require('fs'),assert=require('assert/strict'),vm=require('vm'),{execFileSync}=require('child_process');
const read=p=>fs.readFileSync(p,'utf8'),app=read('app.js'),html=read('index.html');
const baseline='91fe23c88cc81836a797dad33ee2badd8b649a4c';
assert.equal(execFileSync('git',['rev-parse','stable-v10.44^{}'],{encoding:'utf8'}).trim(),baseline);execFileSync('git',['merge-base','--is-ancestor',baseline,'HEAD']);
function source(name,text=app){const start=text.search(new RegExp(`^(?:async )?function ${name}\\(`,'m'));assert(start>=0,name);const rest=text.slice(start),next=rest.slice(1).search(/\n(?:async )?function /);return next<0?rest:rest.slice(0,next+1);}
const old=execFileSync('git',['show',`${baseline}:app.js`],{encoding:'utf8'});
for(const name of ['coachingDataVisibility','coachingCanSeeLiveOwner','coachingDriverTrail','coachingMemberCapabilities','validateCoachingMembers','saveCoachingDriverFeedback','startCoachingDriverTrackHold','reportActivitySource'])assert.equal(source(name),source(name,old),`${name}: baseline security/workflow preserved`);
const dry=read('PISTE_V10.45_PATCH/PISTE_V10.45_DRY_RUN.sql'),sql=read('PISTE_V10.45_PATCH/PISTE_V10.45_APPLY.sql'),legacy=read('PISTE_V10.42.3_PATCH/PISTE_V10.42.3_VISIBILITY_APPLY.sql');
assert.equal(dry.replace(/rollback;\s*$/,'END'),sql.replace(/commit;\s*$/,'END'));
assert(/rollback;\s*$/.test(dry)&&/commit;\s*$/.test(sql));
assert(sql.includes('alter table private.coaching_deferred_v1045 enable row level security'));
assert(sql.includes('revoke all on table private.coaching_deferred_v1045 from public,anon,authenticated'));
assert(!/create policy|drop policy|disable row level|alter table public|grant (?:select|all|update|insert|truncate|trigger|references)/i.test(sql));
assert.equal((sql.match(/security definer set search_path=''/g)||[]).length,6);
assert(sql.includes("without_route:=p_blind_mode='full_blind'"));assert(sql.includes("and m->>'role' in ('coach','driver'));"));assert(sql.includes("if p_route_id is not null then raise exception"));
for(const rule of ["m->>'role'='driver')<>1","m->>'role'='traceur')<>1","Chaque personne doit apparaître une seule fois","Cette personne ne fait pas partie de vos amis"])assert(sql.includes(rule));
for(const field of ['planned_route','planned_markers','odor_model']){const pattern=new RegExp(`'${field}',case when private.coaching_truth_v10423\\(s.id\\)[^\\n]+`);assert.equal(sql.match(pattern)?.[0],legacy.match(pattern)?.[0]);}
assert(sql.includes("me.invitation_status<>'declined'"));assert(sql.includes("me.invitation_status in ('accepted','active')"));assert(sql.includes('private.legacy_get_my_coaching_sessions_v10423(s.id)'));
assert(sql.includes("where session_id=s.id and departure_point='{}'::jsonb"));assert(sql.includes("set departure_point=jsonb_build_object('lat',new.lat,'lon',new.lon)"));
assert(sql.includes("new.owner_id is distinct from (select auth.uid())"));assert(sql.includes("m.role='traceur' and m.invitation_status in ('accepted','active')"));
assert(sql.includes("if d.traceur_ready_at is not null then return public.get_my_coaching_sessions"));assert(sql.includes('set traceur_ready_at=clock_timestamp()'));
assert(sql.includes("new.phase='driver_running' and d.search_mode='deferred'"));assert(sql.includes("d.traceur_ready_at is null or old.track_finished_at is null"));assert(sql.includes("before update on public.coaching_sessions"));
for(const table of ['coaching_trace_points','coaching_live_points','coaching_current_positions'])assert(sql.includes(`before insert or update on public.${table}`));
assert(sql.includes("tg_table_name='coaching_trace_points' and s.phase<>'laying'"));assert(sql.includes("s.phase<>'driver_running'"));assert(sql.includes('for update'));
assert(!sql.includes('insert into public.coaching_messages'),'Single readiness event, no duplicate chat notifications');
for(const key of ['laying_started_at','track_finished_at','driver_started_at','driver_finished_at','ended_at'])assert(sql.includes(`new.${key}:=clock_timestamp()`));
assert(!/new\.phase\s*:=|new\.status\s*:=|update public.coaching_sessions set phase/.test(sql),'Existing phase transitions stay authoritative');
const changed=execFileSync('git',['diff',baseline,'--name-only'],{encoding:'utf8'}).trim().split('\n');assert(!changed.some(p=>p.startsWith('supabase/functions/')||p.endsWith('.sql')&&!/^PISTE_V10\.45_PATCH\/PISTE_V10\.45_(?:DRY_RUN|APPLY)\.sql$/.test(p)));
const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(ids.length,new Set(ids).size);for(const id of ['coachingRouteFields','coachingNoRouteInfo','coachingSearchMode','traceurInPlaceBtn','coachingDeferredInfo'])assert(ids.includes(id));
assert(html.includes('Recherche immédiate')&&html.includes('Recherche différée'));assert(html.indexOf('id="traceurInPlaceBtn"')>html.indexOf('id="coachingPrimaryActions"'));assert(html.indexOf('id="traceurInPlaceBtn"')<html.indexOf('data-coaching-panel="session"'));require('./verify-current-assets')();
const elements=new Map(),storage=new Map(),calls=[],watches=[];
const node=id=>{if(!elements.has(id))elements.set(id,{value:'',innerHTML:'',textContent:'',disabled:false,classList:{hidden:false,add(){this.hidden=true},remove(){this.hidden=false},toggle(_,value){this.hidden=value}},querySelectorAll:()=>[]});return elements.get(id);};
const session={id:'session',visibility_version:3,workflow_version:2,blind_mode:'full_blind',search_mode:'deferred',phase:'waiting_ready',status:'waiting',track_finished_at:'2026-09-10T08:00:00.125Z',laying_started_at:'2026-09-10T07:30:00Z',coaching_members:[{user_id:'coach',role:'coach',invitation_status:'accepted'},{user_id:'traceur',role:'traceur',invitation_status:'accepted'},{user_id:'driver',role:'driver',invitation_status:'accepted'}]};
const ctx=vm.createContext({console,Date,Set,Map,Number,String,session:{user:{id:'coach'}},activeCoachingSession:session,$:node,localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},coachingReadyNoticesV1045:new Set(),coachingPreviewWatch:null,coachingPresenceWatch:null,traceurWatch:null,coachingPreviewPosition:null,navigator:{geolocation:{watchPosition:fn=>(watches.push(fn),1),clearWatch:id=>calls.push(['clear',id])}},formatExactDuration:ms=>String(ms),dateTimeFr:x=>x,esc:x=>x,coachingToast:x=>calls.push(['notice',x]),stopCoachingPresence:()=>{ctx.coachingPresenceWatch=null;calls.push(['stopDriver']);},stopTraceurTracking:()=>{ctx.traceurWatch=null;calls.push(['stopTraceur']);},coachingGpsRole:()=>ctx.myCoachingRole(ctx.activeCoachingSession),coachingCreateInFlight:false,trainingRoutes:[],coachingFriendInvites:[],setUiText:(id,text)=>node(id).textContent=text,validateCoachingConfigurationV10423:()=>({ok:true}),coachingCreationMembers:()=>session.coaching_members,loadCoachingHub:async()=>{},openCoachingSession:async()=>{},renderCoachingFriendInvites:()=>{},markCoachingSyncV10423:()=>{}});
for(const name of ['coachingPhase','myCoachingRole','coachingWithoutPreparedRouteV1045','updateCoachingCreationV1045','coachingTimingV1045','coachingTimestampV1045','coachingDeferredNoPreviewV1045','coachingSearchLabelV1045','coachingReadyNoticeV1045','syncCoachingDeferredV1045','requestCoachingPreviewLocation','startCoachingPresence','createCoaching','missionAge','missionTimeline'])vm.runInContext(source(name),ctx);
(async()=>{
 node('coachingCreatorRole').value='coach';node('coachingVisibility').value='full_blind';node('coachingSearchMode').value='deferred';ctx.updateCoachingCreationV1045();assert(node('coachingRouteFields').classList.hidden);
 let complete;ctx.supabase={rpc:async(name,args)=>{calls.push({name,args});return new Promise(resolve=>complete=resolve);}};const creating=ctx.createCoaching();await ctx.createCoaching();assert.equal(calls.filter(c=>c.name).length,1);assert.equal(calls.at(-1).args.p_route_id,null);assert.equal(calls.at(-1).args.p_search_mode,'deferred');assert.equal(calls.at(-1).args.p_members[0].role,'coach');complete({data:{id:'created'}});await creating;assert(!ctx.coachingCreateInFlight);
 // A creator Conducteur must ignore even a previously selected personal route.
 ctx.session.user.id='driver';node('coachingCreatorRole').value='driver';node('coachingRouteSelect').value='stale-route';ctx.trainingRoutes=[{id:'stale-route',route:[{lat:1,lon:2},{lat:2,lon:3}]}];
 ctx.updateCoachingCreationV1045();assert(node('coachingRouteFields').classList.hidden,'Double aveugle + creator_role=driver: aucun contrôle planned_route visible');
 ctx.supabase={rpc:async(name,args)=>{calls.push({name,args});return {data:{id:'driver-created'}};}};
 await ctx.createCoaching();assert.equal(calls.at(-1).args.p_route_id,null,'Driver cannot send a stale planned_route');
 ctx.trainingRoutes=[];await ctx.createCoaching();assert.equal(calls.at(-1).args.p_route_id,null,'Driver creation requires no planned_route');
 node('coachingCreatorRole').value='traceur';ctx.updateCoachingCreationV1045();assert(!node('coachingRouteFields').classList.hidden,'Traceur retains route controls');
 for(const role of ['coach','driver','traceur'])for(const mode of ['normal','simple_blind']){node('coachingCreatorRole').value=role;node('coachingVisibility').value=mode;ctx.updateCoachingCreationV1045();assert(!node('coachingRouteFields').classList.hidden);assert(!ctx.coachingWithoutPreparedRouteV1045());}
 node('coachingCreatorRole').value='driver';
 for(const mode of ['normal','simple_blind']){node('coachingVisibility').value=mode;ctx.updateCoachingCreationV1045();assert(!node('coachingRouteFields').classList.hidden);assert(!ctx.coachingWithoutPreparedRouteV1045());}
 for(const user of ['coach','traceur','driver']){ctx.session.user.id=user;for(const phase of ['preparation','laying','waiting_ready']){ctx.activeCoachingSession={...session,phase,status:phase==='laying'?'live':'waiting'};assert.equal(await ctx.requestCoachingPreviewLocation(),false);if(user==='driver')ctx.startCoachingPresence();}}assert.equal(watches.length,0,'No GPS started in deferred wait, including driver while Traceur lays');
 ctx.activeCoachingSession={...session};ctx.session.user.id='traceur';ctx.syncCoachingDeferredV1045();assert(!node('traceurInPlaceBtn').classList.hidden);
 ctx.session.user.id='coach';ctx.syncCoachingDeferredV1045();assert(node('traceurInPlaceBtn').classList.hidden);
 ctx.session.user.id='driver';ctx.coachingPreviewWatch=9;ctx.coachingPresenceWatch=10;ctx.traceurWatch=11;ctx.syncCoachingDeferredV1045();assert.equal(ctx.coachingPreviewWatch,null);assert.equal(ctx.coachingPresenceWatch,null);assert.equal(ctx.traceurWatch,null);assert(node('driverStartBtn').classList.hidden);
 const waiting=ctx.coachingTimingV1045(session,Date.parse('2026-09-10T12:00:00.125Z'));assert.equal(waiting.waitingMs,14400000);assert.equal(waiting.ageAtStartMs,null);assert.equal(ctx.coachingTimingV1045({...session,server_now:'2026-09-10T12:00:00.125Z',_received_at:1000},2000).waitingMs,14401000,'Server time anchors waiting despite device clock offset');
 ctx.activeCoachingSession.traceur_ready_at='2026-09-10T11:59:00Z';ctx.syncCoachingDeferredV1045();ctx.syncCoachingDeferredV1045();assert.equal(calls.filter(c=>c[0]==='notice').length,1);ctx.coachingReadyNoticesV1045=new Set();ctx.syncCoachingDeferredV1045();assert.equal(calls.filter(c=>c[0]==='notice').length,1,'No duplicate notification after reload on this device');
 const running={...ctx.activeCoachingSession,phase:'driver_running',status:'live',driver_started_at:'2026-09-10T12:00:00.625Z'};assert.equal(ctx.coachingTimingV1045(running).ageAtStartMs,14400500);assert.equal(ctx.coachingTimingV1045(running,Date.parse('2026-09-11')).waitingMs,14400500);assert(!ctx.coachingDeferredNoPreviewV1045(running));assert(!ctx.coachingDeferredNoPreviewV1045({...session,search_mode:'immediate'}));
 ctx.hasValue=x=>x!==undefined&&x!==null;assert.equal(ctx.missionAge({type:'coaching',row:running,actual:[],trace:[]}),String(14400500));assert.equal(ctx.missionAge({type:'coaching',row:{laying_started_at:session.laying_started_at,driver_started_at:running.driver_started_at},actual:[],trace:[]}),null);
 ctx.LIVE_MARKERS={};const timeline=ctx.missionTimeline({type:'coaching',row:{...running,driver_finished_at:'2026-09-10T12:20:00Z',ended_at:'2026-09-10T12:30:00Z'},markers:[]});for(const title of ['Début du traçage','Piste tracée','Attente différée','Traceur en place','Départ Conducteur','Fin de parcours','Clôture de la session'])assert(timeline.some(e=>e.title===title));assert.equal(timeline.find(e=>e.title==='Attente différée').detail,String(14400500));
 assert(source('openCoachingSession').includes('let s=null;'));assert(source('openCoachingSession').includes("supabase.rpc('get_my_coaching_sessions'"));assert(source('handleHomeCoachingAction').includes("action==='deferred'"));assert(source('handleCoachingSessionChange').includes('refreshActiveCoachingSession(id)'));
 const finishSource=source('saveCoachingDriverFeedback');assert(finishSource.includes('finalizeSavedCoachingSession'));assert(source('finalizeSavedCoachingSession').includes('finish_coaching_session'));assert(html.includes('Terminer la piste<small>Maintenir 2 secondes'));assert(html.includes('Enregistrer ma piste'));
 execFileSync(process.execPath,['scripts/check-postgres-sql.js','PISTE_V10.45_PATCH/PISTE_V10.45_DRY_RUN.sql','PISTE_V10.45_PATCH/PISTE_V10.45_APPLY.sql'],{stdio:'inherit'});
 console.log('V10.45 A–J local OK: no-route Coach, exact delay, roles, wait without GPS, one notification, restart projection, immutable workflow, timeline, SQL guards, HTML/cache.');
 console.log('SQL NOT executed. Server concurrency/permissions and physical iPhone Safari require manual recipe after APPLY.');
})().catch(error=>{console.error(error);process.exitCode=1});
