// Offline browser fixture: production presentation functions, synthetic authorized records.
// Usage: node scripts/fixture-v10-43.js /private/tmp/piste-v1043.html
const fs=require('fs'),path=require('path');const app=fs.readFileSync('app.js','utf8'),html=fs.readFileSync('index.html','utf8');
function source(name){const start=app.search(new RegExp(`(?:async )?function ${name}\\(`));if(start<0)throw Error(name);const rest=app.slice(start),next=rest.slice(1).search(/\n(?:(?:async )?function \w+\(|const |let |\/\*)/);return name==='setMissionMapExpanded'?rest.split('\n')[0]:next<0?rest:rest.slice(0,next+1)}
const names=[...app.matchAll(/^(?:async )?function (mission\w+|closeMissionDossier|openMissionDossier|renderMission\w+|setMissionTab|updateMissionLibraryFilters)\(/gm)].map(x=>x[1]);
names.push('feedTrackPreview','setMissionMapExpanded','reportActivitySource','libraryTypeMeta','libraryName','libraryTrackDistanceKm','reportHuman','reportLines','reportRoleLabel','reportWeatherText','markerChronology','reportSection','buildProfessionalReportModel','reportMapCanvas','safePdfName','pdfAddPageIfNeeded','buildProfessionalPdfBlob','dateTimeFr','hav','activityLibraryRows','activityLibraryCard','libraryThumbnail','libraryTrack','libraryOwned','libraryVisibility','libraryVisibilityLabel','libraryStatsHtml','bindLibraryCards','renderActivityLibrary','activityDate','openLibraryItem','updateLibrarySelectionUi');
const sections=['missionPage','libraryPage'].map(id=>html.match(new RegExp(`<section id="${id}"[\\s\\S]*?</section>\\s*(?=\\n\\s*(?:<section|<div|$))`))?.[0]);
// Mission has nested sections: use the next top-level page boundary.
sections[0]=html.slice(html.indexOf('  <section id="missionPage"'),html.indexOf('  <section id="activityDetailPage"'));
sections[1]=html.slice(html.indexOf('  <section id="libraryPage"'),html.indexOf('  <section id="trainingPage"'));
const fixture=`<!doctype html><html lang="fr"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>V10.43 fixture</title><style>${fs.readFileSync('styles.css','utf8')}\n${fs.readFileSync('v2.css','utf8')}</style><link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"><script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><script src="https://cdn.jsdelivr.net/npm/jspdf@2.5.2/dist/jspdf.umd.min.js"></script><body class="v10-30-aurora"><main style="max-width:900px;margin:auto;padding:14px">${sections.join('')}</main>${html.match(/<nav class="bottom-nav">[\s\S]*?<\/nav>/)[0]}<script>
const BLACK_BOX_VERSION='10.43';const $=id=>document.getElementById(id),APP_VERSION='10.43',fmt=(v,d=1)=>Number(v||0).toLocaleString('fr-FR',{maximumFractionDigits:d}),hasValue=v=>v!==null&&v!==undefined&&v!=='',esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),dogDisplay=id=>id==='dog'?'Rex':'',formatExactDuration=ms=>Math.round(ms/60000)+' min',metricText=(v,d,u)=>hasValue(v)?fmt(v,d)+' '+u:'Non renseigné',session={user:{id:'driver'}},coachingStatusLabel=s=>s==='ended'?'Terminé':'En cours',myCoachingRole=()=> 'driver',coachingBlindMode=s=>s.blind_mode;
${app.match(/^const LIVE_MARKERS=.*$/m)[0]}
${app.slice(app.indexOf('const TerrainBlackBox='),app.indexOf('function blackBoxActivity('))}
let missionSource=null,missionMap=null,missionResizeObserver=null,missionLoadSequence=0,activityLibraryFilters={query:'',type:'all',status:'active',favorite:false},activityLibrarySelection=[],activityLibrarySelectionMode=false,activityLibraryView='list',globalMap=null;
const points=[{lat:48.58,lon:7.75,recorded_at:'2026-09-04T12:32:00Z'},{lat:48.582,lon:7.754,recorded_at:'2026-09-04T12:45:00Z'}];
const row={id:'session',name:'Coaching — Forêt Nord',status:'ended',created_at:'2026-09-04T11:00:00Z',laying_started_at:'2026-09-04T11:30:00Z',track_finished_at:'2026-09-04T12:00:00Z',driver_started_at:'2026-09-04T12:32:00Z',driver_finished_at:'2026-09-04T12:45:00Z',ended_at:'2026-09-04T13:00:00Z',planned_route:points,blind_mode:'simple_blind',dog_id:'dog',coaching_members:[{user_id:'driver',role:'driver',display_name:'Alex'},{user_id:'traceur',role:'traceur',display_name:'Camille'},{user_id:'coach',role:'coach',display_name:'Sam'}]};
const mine=[{id:'ops',operational_call_id:'call',activity_name:'OPS — Recherche forêt',owner_id:'driver',date:'2026-09-03',dog_id:'dog',track:points,observation:'Recherche terminée.',distance_km:1.2,duree_h:.5}],trainings=[{id:'training',activity_name:'Entraînement libre',owner_id:'driver',date:'2026-09-02',track:points}],coachingSessions=[row],trainingRoutes=[{id:'prepared',name:'Tracé préparé',route:points,owner_id:'driver'}];
const libraryRow=(type,id)=>({operational:mine,training:trainings,coaching:coachingSessions,prepared:trainingRoutes})[type].find(x=>x.id===id);
let requests=[];const supabase={rpc:async(name,args)=>{requests.push(name);return {data:[row]}},from:table=>{requests.push(table);const q={select:()=>q,eq:()=>q,order:()=>q,range:()=>q,maybeSingle:()=>q,then:resolve=>resolve({data:table==='operational_calls'?{call_at:'2026-09-03T09:00:00Z',urgency:'standard',circumstances:'Recherche sur secteur forestier',imported_tracks:[{name:'Secteur Nord',points,visible:true}]}:table==='coaching_live_points'?points.map(p=>({...p,owner_id:'driver'})):table==='coaching_trace_points'?points.map(p=>({...p,lon:p.lon+.001})):table==='coaching_markers'?[{id:'marker',lat:48.581,lon:7.752,marker_type:'loss',note:'Recherche du départ',created_at:'2026-09-04T12:38:00Z'}]:{driver_notes:'Retour indépendant du Conducteur.',coach_notes:'Analyse indépendante du Coach.',updated_at:'2026-09-04T13:05:00Z'}})};return q}};
function showPage(id){if(id!=='missionPage')closeMissionDossier();document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===id));if(id==='libraryPage')renderActivityLibrary()}
function createPisteMap(id){return L.map(id)}function addCleanBaseLayers(map){L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map)}
${names.map(source).join('\n')}
$('missionBack').onclick=()=>showPage('libraryPage');document.querySelectorAll('[data-mission-tab]').forEach(b=>b.onclick=()=>setMissionTab(b.dataset.missionTab));document.querySelectorAll('[data-library-filter]').forEach(b=>b.onclick=()=>{activityLibraryFilters.type=b.dataset.libraryFilter;renderActivityLibrary()});$('librarySearch').oninput=e=>{activityLibraryFilters.query=e.target.value;renderActivityLibrary()};for(const id of ['missionSort','missionDog','missionSince','missionUntil'])$(id).onchange=()=>renderActivityLibrary();showPage('libraryPage');
</script></body></html>`;
const output=process.argv[2];if(!output)throw Error('Output path required');fs.writeFileSync(output,fixture);console.log(path.resolve(output));
